Backup failed for Site learning.test. Database or site_config.json may be corrupted
Backup failed for Site learning.test. Database or site_config.json may be corrupted
Traceback with variables (most recent call last):
  File "apps/frappe/frappe/commands/site.py", line 865, in backup
    odb = scheduled_backup(
      context = CliCtxObj(sites=['learning.test'], force=False, profile=False, verbose=True)
      with_files = False
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_backup_conf = False
      verbose = True
      compress = False
      include = ''
      exclude = ''
      old_backup_metadata = False
      scheduled_backup = <function scheduled_backup at 0x10344f560>
      exit_code = 0
      rollback_callback = None
      site = 'learning.test'
  File "apps/frappe/frappe/utils/backups.py", line 589, in scheduled_backup
    return new_backup(
      older_than = 6
      ignore_files = True
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_conf = False
      include_doctypes = ''
      exclude_doctypes = ''
      compress = False
      force = True
      verbose = True
      old_backup_metadata = False
      rollback_callback = <frappe.utils.CallbackManager object at 0x103625c00>
  File "apps/frappe/frappe/utils/backups.py", line 647, in new_backup
    odb.get_backup(older_than, ignore_files, force=force)
      older_than = 6
      ignore_files = True
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_conf = False
      include_doctypes = ''
      exclude_doctypes = ''
      compress = False
      force = True
      verbose = True
      old_backup_metadata = False
      rollback_callback = <frappe.utils.CallbackManager object at 0x103625c00>
      odb = <frappe.utils.backups.BackupGenerator object at 0x10363c2f0>
  File "apps/frappe/frappe/utils/backups.py", line 191, in get_backup
    self.delete_if_step_fails(self.take_dump, self.backup_path_db)
      self = <frappe.utils.backups.BackupGenerator object at 0x10363c2f0>
      older_than = 6
      ignore_files = True
      force = True
      last_db = False
      last_file = False
      last_private_file = False
      site_config_backup_path = False
  File "apps/frappe/frappe/utils/backups.py", line 528, in delete_if_step_fails
    raise e
      self = <frappe.utils.backups.BackupGenerator object at 0x10363c2f0>
      step = <bound method BackupGenerator.take_dump of <frappe.utils.backups.BackupGenerator object at 0x10363c2f0>>
      paths = ('./learning.test/private/backups/20250619_194110-learning_test-database.sql.gz',)
      path = './learning.test/private/backups/20250619_194110-learning_test-database.sql.gz'
  File "apps/frappe/frappe/utils/backups.py", line 523, in delete_if_step_fails
    step()
      self = <frappe.utils.backups.BackupGenerator object at 0x10363c2f0>
      step = <bound method BackupGenerator.take_dump of <frappe.utils.backups.BackupGenerator object at 0x10363c2f0>>
      paths = ('./learning.test/private/backups/20250619_194110-learning_test-database.sql.gz',)
      path = './learning.test/private/backups/20250619_194110-learning_test-database.sql.gz'
  File "apps/frappe/frappe/utils/backups.py", line 465, in take_dump
    frappe.throw(
      self = <frappe.utils.backups.BackupGenerator object at 0x10363c2f0>
      frappe = <module 'frappe' from 'apps/frappe/frappe/__init__.py'>
      shlex = <module 'shlex' from '/opt/homebrew/Cellar/python@3.13/3.13.5/Frameworks/Python.framework/Versions/3.13/lib/python3.13/shlex.py'>
      get_app_branch = <function get_app_branch at 0x1036eeac0>
      gzip_exc = '/usr/bin/gzip'
      database_header_content = ['begin frappe metadata', '[frappe]', 'version = 16.0.0-dev', 'branch = develop', 'end frappe metadata', '']
      generated_header = '-- begin frappe metadata\n-- [frappe]\n-- version = 16.0.0-dev\n-- branch = develop\n-- end frappe metadata\n-- \n'
      f = <_io.TextIOWrapper name='./learning.test/private/backups/20250619_194110-learning_test-database.sql.gz' encoding='UTF-8'>
      cmd = []
      extra = []
      get_command = <function get_command at 0x1034bd260>
      bin = None
      args = ['--user=_e1faab4bbb015fc1', '--host=127.0.0.1', '--port=3306', '--password=hEEDuC879iaZlv31', '--single-transaction', '--quick', '--lock-tables=false', '_e1faab4bbb015fc1']
      bin_name = 'mariadb-dump'
  File "apps/frappe/frappe/utils/messages.py", line 145, in throw
    msgprint(
      msg = 'mariadb-dump not found in PATH! This is required to take a backup.'
      exc = <class 'frappe.exceptions.ExecutableNotFound'>
      title = None
      is_minimizable = False
      wide = False
      as_list = False
      primary_action = None
  File "apps/frappe/frappe/utils/messages.py", line 106, in msgprint
    _raise_exception()
      msg = 'mariadb-dump not found in PATH! This is required to take a backup.'
      title = None
      raise_exception = <class 'frappe.exceptions.ExecutableNotFound'>
      as_table = False
      as_list = False
      indicator = 'red'
      alert = False
      primary_action = None
      is_minimizable = False
      wide = False
      realtime = False
      _raise_exception = <function msgprint.<locals>._raise_exception at 0x1036ecea0>
      inspect = <module 'inspect' from '/opt/homebrew/Cellar/python@3.13/3.13.5/Frameworks/Python.framework/Versions/3.13/lib/python3.13/inspect.py'>
      out = {'message': 'mariadb-dump not found in PATH! This is required to take a backup.', 'title': 'Message', 'indicator': 'red', 'raise_exception': 1, '__frappe_exc_id': 'f7806e8cd7b2161a0a974bc258e160ac30a637da460c497ac6c7665b'}
  File "apps/frappe/frappe/utils/messages.py", line 57, in _raise_exception
    raise exc
      exc = ExecutableNotFound('mariadb-dump not found in PATH! This is required to take a backup.')
      inspect = <module 'inspect' from '/opt/homebrew/Cellar/python@3.13/3.13.5/Frameworks/Python.framework/Versions/3.13/lib/python3.13/inspect.py'>
      msg = 'mariadb-dump not found in PATH! This is required to take a backup.'
      out = {'message': 'mariadb-dump not found in PATH! This is required to take a backup.', 'title': 'Message', 'indicator': 'red', 'raise_exception': 1, '__frappe_exc_id': 'f7806e8cd7b2161a0a974bc258e160ac30a637da460c497ac6c7665b'}
      raise_exception = <class 'frappe.exceptions.ExecutableNotFound'>
frappe.exceptions.ExecutableNotFound: mariadb-dump not found in PATH! This is required to take a backup.
Traceback with variables (most recent call last):
  File "apps/frappe/frappe/commands/site.py", line 865, in backup
    odb = scheduled_backup(
      context = CliCtxObj(sites=['learning.test'], force=False, profile=False, verbose=True)
      with_files = False
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_backup_conf = False
      verbose = True
      compress = False
      include = ''
      exclude = ''
      old_backup_metadata = False
      scheduled_backup = <function scheduled_backup at 0x1064e7560>
      exit_code = 0
      rollback_callback = None
      site = 'learning.test'
  File "apps/frappe/frappe/utils/backups.py", line 589, in scheduled_backup
    return new_backup(
      older_than = 6
      ignore_files = True
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_conf = False
      include_doctypes = ''
      exclude_doctypes = ''
      compress = False
      force = True
      verbose = True
      old_backup_metadata = False
      rollback_callback = <frappe.utils.CallbackManager object at 0x1066bdba0>
  File "apps/frappe/frappe/utils/backups.py", line 647, in new_backup
    odb.get_backup(older_than, ignore_files, force=force)
      older_than = 6
      ignore_files = True
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_conf = False
      include_doctypes = ''
      exclude_doctypes = ''
      compress = False
      force = True
      verbose = True
      old_backup_metadata = False
      rollback_callback = <frappe.utils.CallbackManager object at 0x1066bdba0>
      odb = <frappe.utils.backups.BackupGenerator object at 0x1066d42f0>
  File "apps/frappe/frappe/utils/backups.py", line 191, in get_backup
    self.delete_if_step_fails(self.take_dump, self.backup_path_db)
      self = <frappe.utils.backups.BackupGenerator object at 0x1066d42f0>
      older_than = 6
      ignore_files = True
      force = True
      last_db = False
      last_file = False
      last_private_file = False
      site_config_backup_path = False
  File "apps/frappe/frappe/utils/backups.py", line 528, in delete_if_step_fails
    raise e
      self = <frappe.utils.backups.BackupGenerator object at 0x1066d42f0>
      step = <bound method BackupGenerator.take_dump of <frappe.utils.backups.BackupGenerator object at 0x1066d42f0>>
      paths = ('./learning.test/private/backups/20250619_194110-learning_test-database.sql.gz',)
      path = './learning.test/private/backups/20250619_194110-learning_test-database.sql.gz'
  File "apps/frappe/frappe/utils/backups.py", line 523, in delete_if_step_fails
    step()
      self = <frappe.utils.backups.BackupGenerator object at 0x1066d42f0>
      step = <bound method BackupGenerator.take_dump of <frappe.utils.backups.BackupGenerator object at 0x1066d42f0>>
      paths = ('./learning.test/private/backups/20250619_194110-learning_test-database.sql.gz',)
      path = './learning.test/private/backups/20250619_194110-learning_test-database.sql.gz'
  File "apps/frappe/frappe/utils/backups.py", line 465, in take_dump
    frappe.throw(
      self = <frappe.utils.backups.BackupGenerator object at 0x1066d42f0>
      frappe = <module 'frappe' from 'apps/frappe/frappe/__init__.py'>
      shlex = <module 'shlex' from '/opt/homebrew/Cellar/python@3.13/3.13.5/Frameworks/Python.framework/Versions/3.13/lib/python3.13/shlex.py'>
      get_app_branch = <function get_app_branch at 0x106786ac0>
      gzip_exc = '/usr/bin/gzip'
      database_header_content = ['begin frappe metadata', '[frappe]', 'version = 16.0.0-dev', 'branch = develop', 'end frappe metadata', '']
      generated_header = '-- begin frappe metadata\n-- [frappe]\n-- version = 16.0.0-dev\n-- branch = develop\n-- end frappe metadata\n-- \n'
      f = <_io.TextIOWrapper name='./learning.test/private/backups/20250619_194110-learning_test-database.sql.gz' encoding='UTF-8'>
      cmd = []
      extra = []
      get_command = <function get_command at 0x106555260>
      bin = None
      args = ['--user=_e1faab4bbb015fc1', '--host=127.0.0.1', '--port=3306', '--password=hEEDuC879iaZlv31', '--single-transaction', '--quick', '--lock-tables=false', '_e1faab4bbb015fc1']
      bin_name = 'mariadb-dump'
  File "apps/frappe/frappe/utils/messages.py", line 145, in throw
    msgprint(
      msg = 'mariadb-dump not found in PATH! This is required to take a backup.'
      exc = <class 'frappe.exceptions.ExecutableNotFound'>
      title = None
      is_minimizable = False
      wide = False
      as_list = False
      primary_action = None
  File "apps/frappe/frappe/utils/messages.py", line 106, in msgprint
    _raise_exception()
      msg = 'mariadb-dump not found in PATH! This is required to take a backup.'
      title = None
      raise_exception = <class 'frappe.exceptions.ExecutableNotFound'>
      as_table = False
      as_list = False
      indicator = 'red'
      alert = False
      primary_action = None
      is_minimizable = False
      wide = False
      realtime = False
      _raise_exception = <function msgprint.<locals>._raise_exception at 0x106784ea0>
      inspect = <module 'inspect' from '/opt/homebrew/Cellar/python@3.13/3.13.5/Frameworks/Python.framework/Versions/3.13/lib/python3.13/inspect.py'>
      out = {'message': 'mariadb-dump not found in PATH! This is required to take a backup.', 'title': 'Message', 'indicator': 'red', 'raise_exception': 1, '__frappe_exc_id': '5ba3cc1fd29d7e988e932d9dd37b0f7429cbf4baab74914cc0c2b1cf'}
  File "apps/frappe/frappe/utils/messages.py", line 57, in _raise_exception
    raise exc
      exc = ExecutableNotFound('mariadb-dump not found in PATH! This is required to take a backup.')
      inspect = <module 'inspect' from '/opt/homebrew/Cellar/python@3.13/3.13.5/Frameworks/Python.framework/Versions/3.13/lib/python3.13/inspect.py'>
      msg = 'mariadb-dump not found in PATH! This is required to take a backup.'
      out = {'message': 'mariadb-dump not found in PATH! This is required to take a backup.', 'title': 'Message', 'indicator': 'red', 'raise_exception': 1, '__frappe_exc_id': '5ba3cc1fd29d7e988e932d9dd37b0f7429cbf4baab74914cc0c2b1cf'}
      raise_exception = <class 'frappe.exceptions.ExecutableNotFound'>
frappe.exceptions.ExecutableNotFound: mariadb-dump not found in PATH! This is required to take a backup.
Backup failed for Site learning.test. Database or site_config.json may be corrupted
Traceback with variables (most recent call last):
  File "apps/frappe/frappe/commands/site.py", line 865, in backup
    odb = scheduled_backup(
      context = CliCtxObj(sites=['learning.test'], force=False, profile=False, verbose=True)
      with_files = False
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_backup_conf = False
      verbose = True
      compress = False
      include = ''
      exclude = ''
      old_backup_metadata = False
      scheduled_backup = <function scheduled_backup at 0x105a73560>
      exit_code = 0
      rollback_callback = None
      site = 'learning.test'
  File "apps/frappe/frappe/utils/backups.py", line 589, in scheduled_backup
    return new_backup(
      older_than = 6
      ignore_files = True
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_conf = False
      include_doctypes = ''
      exclude_doctypes = ''
      compress = False
      force = True
      verbose = True
      old_backup_metadata = False
      rollback_callback = <frappe.utils.CallbackManager object at 0x105c45db0>
  File "apps/frappe/frappe/utils/backups.py", line 647, in new_backup
    odb.get_backup(older_than, ignore_files, force=force)
      older_than = 6
      ignore_files = True
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_conf = False
      include_doctypes = ''
      exclude_doctypes = ''
      compress = False
      force = True
      verbose = True
      old_backup_metadata = False
      rollback_callback = <frappe.utils.CallbackManager object at 0x105c45db0>
      odb = <frappe.utils.backups.BackupGenerator object at 0x105c602f0>
  File "apps/frappe/frappe/utils/backups.py", line 191, in get_backup
    self.delete_if_step_fails(self.take_dump, self.backup_path_db)
      self = <frappe.utils.backups.BackupGenerator object at 0x105c602f0>
      older_than = 6
      ignore_files = True
      force = True
      last_db = False
      last_file = False
      last_private_file = False
      site_config_backup_path = False
  File "apps/frappe/frappe/utils/backups.py", line 528, in delete_if_step_fails
    raise e
      self = <frappe.utils.backups.BackupGenerator object at 0x105c602f0>
      step = <bound method BackupGenerator.take_dump of <frappe.utils.backups.BackupGenerator object at 0x105c602f0>>
      paths = ('./learning.test/private/backups/20250620_033002-learning_test-database.sql.gz',)
      path = './learning.test/private/backups/20250620_033002-learning_test-database.sql.gz'
  File "apps/frappe/frappe/utils/backups.py", line 523, in delete_if_step_fails
    step()
      self = <frappe.utils.backups.BackupGenerator object at 0x105c602f0>
      step = <bound method BackupGenerator.take_dump of <frappe.utils.backups.BackupGenerator object at 0x105c602f0>>
      paths = ('./learning.test/private/backups/20250620_033002-learning_test-database.sql.gz',)
      path = './learning.test/private/backups/20250620_033002-learning_test-database.sql.gz'
  File "apps/frappe/frappe/utils/backups.py", line 465, in take_dump
    frappe.throw(
      self = <frappe.utils.backups.BackupGenerator object at 0x105c602f0>
      frappe = <module 'frappe' from 'apps/frappe/frappe/__init__.py'>
      shlex = <module 'shlex' from '/opt/homebrew/Cellar/python@3.13/3.13.5/Frameworks/Python.framework/Versions/3.13/lib/python3.13/shlex.py'>
      get_app_branch = <function get_app_branch at 0x105c659e0>
      gzip_exc = '/usr/bin/gzip'
      database_header_content = ['begin frappe metadata', '[frappe]', 'version = 16.0.0-dev', 'branch = develop', 'end frappe metadata', '']
      generated_header = '-- begin frappe metadata\n-- [frappe]\n-- version = 16.0.0-dev\n-- branch = develop\n-- end frappe metadata\n-- \n'
      f = <_io.TextIOWrapper name='./learning.test/private/backups/20250620_033002-learning_test-database.sql.gz' encoding='UTF-8'>
      cmd = []
      extra = []
      get_command = <function get_command at 0x105ae1260>
      bin = None
      args = ['--user=_e1faab4bbb015fc1', '--host=127.0.0.1', '--port=3306', '--password=hEEDuC879iaZlv31', '--single-transaction', '--quick', '--lock-tables=false', '_e1faab4bbb015fc1']
      bin_name = 'mariadb-dump'
  File "apps/frappe/frappe/utils/messages.py", line 145, in throw
    msgprint(
      msg = 'mariadb-dump not found in PATH! This is required to take a backup.'
      exc = <class 'frappe.exceptions.ExecutableNotFound'>
      title = None
      is_minimizable = False
      wide = False
      as_list = False
      primary_action = None
  File "apps/frappe/frappe/utils/messages.py", line 106, in msgprint
    _raise_exception()
      msg = 'mariadb-dump not found in PATH! This is required to take a backup.'
      title = None
      raise_exception = <class 'frappe.exceptions.ExecutableNotFound'>
      as_table = False
      as_list = False
      indicator = 'red'
      alert = False
      primary_action = None
      is_minimizable = False
      wide = False
      realtime = False
      _raise_exception = <function msgprint.<locals>._raise_exception at 0x105c64680>
      inspect = <module 'inspect' from '/opt/homebrew/Cellar/python@3.13/3.13.5/Frameworks/Python.framework/Versions/3.13/lib/python3.13/inspect.py'>
      out = {'message': 'mariadb-dump not found in PATH! This is required to take a backup.', 'title': 'Message', 'indicator': 'red', 'raise_exception': 1, '__frappe_exc_id': '860730518e1ab8055b0adcf3110ee5ee3862cc083ea28de4afb7717b'}
  File "apps/frappe/frappe/utils/messages.py", line 57, in _raise_exception
    raise exc
      exc = ExecutableNotFound('mariadb-dump not found in PATH! This is required to take a backup.')
      inspect = <module 'inspect' from '/opt/homebrew/Cellar/python@3.13/3.13.5/Frameworks/Python.framework/Versions/3.13/lib/python3.13/inspect.py'>
      msg = 'mariadb-dump not found in PATH! This is required to take a backup.'
      out = {'message': 'mariadb-dump not found in PATH! This is required to take a backup.', 'title': 'Message', 'indicator': 'red', 'raise_exception': 1, '__frappe_exc_id': '860730518e1ab8055b0adcf3110ee5ee3862cc083ea28de4afb7717b'}
      raise_exception = <class 'frappe.exceptions.ExecutableNotFound'>
frappe.exceptions.ExecutableNotFound: mariadb-dump not found in PATH! This is required to take a backup.
Backup failed for Site learning.test. Database or site_config.json may be corrupted
Traceback with variables (most recent call last):
  File "apps/frappe/frappe/commands/site.py", line 865, in backup
    odb = scheduled_backup(
      context = CliCtxObj(sites=['learning.test'], force=False, profile=False, verbose=True)
      with_files = False
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_backup_conf = False
      verbose = True
      compress = False
      include = ''
      exclude = ''
      old_backup_metadata = False
      scheduled_backup = <function scheduled_backup at 0x1061e7560>
      exit_code = 0
      rollback_callback = None
      site = 'learning.test'
  File "apps/frappe/frappe/utils/backups.py", line 589, in scheduled_backup
    return new_backup(
      older_than = 6
      ignore_files = True
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_conf = False
      include_doctypes = ''
      exclude_doctypes = ''
      compress = False
      force = True
      verbose = True
      old_backup_metadata = False
      rollback_callback = <frappe.utils.CallbackManager object at 0x1061bfb20>
  File "apps/frappe/frappe/utils/backups.py", line 647, in new_backup
    odb.get_backup(older_than, ignore_files, force=force)
      older_than = 6
      ignore_files = True
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_conf = False
      include_doctypes = ''
      exclude_doctypes = ''
      compress = False
      force = True
      verbose = True
      old_backup_metadata = False
      rollback_callback = <frappe.utils.CallbackManager object at 0x1061bfb20>
      odb = <frappe.utils.backups.BackupGenerator object at 0x1064d42f0>
  File "apps/frappe/frappe/utils/backups.py", line 191, in get_backup
    self.delete_if_step_fails(self.take_dump, self.backup_path_db)
      self = <frappe.utils.backups.BackupGenerator object at 0x1064d42f0>
      older_than = 6
      ignore_files = True
      force = True
      last_db = False
      last_file = False
      last_private_file = False
      site_config_backup_path = False
  File "apps/frappe/frappe/utils/backups.py", line 528, in delete_if_step_fails
    raise e
      self = <frappe.utils.backups.BackupGenerator object at 0x1064d42f0>
      step = <bound method BackupGenerator.take_dump of <frappe.utils.backups.BackupGenerator object at 0x1064d42f0>>
      paths = ('./learning.test/private/backups/20250621_093002-learning_test-database.sql.gz',)
      path = './learning.test/private/backups/20250621_093002-learning_test-database.sql.gz'
  File "apps/frappe/frappe/utils/backups.py", line 523, in delete_if_step_fails
    step()
      self = <frappe.utils.backups.BackupGenerator object at 0x1064d42f0>
      step = <bound method BackupGenerator.take_dump of <frappe.utils.backups.BackupGenerator object at 0x1064d42f0>>
      paths = ('./learning.test/private/backups/20250621_093002-learning_test-database.sql.gz',)
      path = './learning.test/private/backups/20250621_093002-learning_test-database.sql.gz'
  File "apps/frappe/frappe/utils/backups.py", line 465, in take_dump
    frappe.throw(
      self = <frappe.utils.backups.BackupGenerator object at 0x1064d42f0>
      frappe = <module 'frappe' from 'apps/frappe/frappe/__init__.py'>
      shlex = <module 'shlex' from '/opt/homebrew/Cellar/python@3.13/3.13.5/Frameworks/Python.framework/Versions/3.13/lib/python3.13/shlex.py'>
      get_app_branch = <function get_app_branch at 0x1064d99e0>
      gzip_exc = '/usr/bin/gzip'
      database_header_content = ['begin frappe metadata', '[frappe]', 'version = 16.0.0-dev', 'branch = develop', 'end frappe metadata', '']
      generated_header = '-- begin frappe metadata\n-- [frappe]\n-- version = 16.0.0-dev\n-- branch = develop\n-- end frappe metadata\n-- \n'
      f = <_io.TextIOWrapper name='./learning.test/private/backups/20250621_093002-learning_test-database.sql.gz' encoding='UTF-8'>
      cmd = []
      extra = []
      get_command = <function get_command at 0x106355260>
      bin = None
      args = ['--user=_e1faab4bbb015fc1', '--host=127.0.0.1', '--port=3306', '--password=hEEDuC879iaZlv31', '--single-transaction', '--quick', '--lock-tables=false', '_e1faab4bbb015fc1']
      bin_name = 'mariadb-dump'
  File "apps/frappe/frappe/utils/messages.py", line 145, in throw
    msgprint(
      msg = 'mariadb-dump not found in PATH! This is required to take a backup.'
      exc = <class 'frappe.exceptions.ExecutableNotFound'>
      title = None
      is_minimizable = False
      wide = False
      as_list = False
      primary_action = None
  File "apps/frappe/frappe/utils/messages.py", line 106, in msgprint
    _raise_exception()
      msg = 'mariadb-dump not found in PATH! This is required to take a backup.'
      title = None
      raise_exception = <class 'frappe.exceptions.ExecutableNotFound'>
      as_table = False
      as_list = False
      indicator = 'red'
      alert = False
      primary_action = None
      is_minimizable = False
      wide = False
      realtime = False
      _raise_exception = <function msgprint.<locals>._raise_exception at 0x1064d8680>
      inspect = <module 'inspect' from '/opt/homebrew/Cellar/python@3.13/3.13.5/Frameworks/Python.framework/Versions/3.13/lib/python3.13/inspect.py'>
      out = {'message': 'mariadb-dump not found in PATH! This is required to take a backup.', 'title': 'Message', 'indicator': 'red', 'raise_exception': 1, '__frappe_exc_id': 'ec81987752a4992bd6a3e2e15384ec33ddf5471d0287a20d8664c327'}
  File "apps/frappe/frappe/utils/messages.py", line 57, in _raise_exception
    raise exc
      exc = ExecutableNotFound('mariadb-dump not found in PATH! This is required to take a backup.')
      inspect = <module 'inspect' from '/opt/homebrew/Cellar/python@3.13/3.13.5/Frameworks/Python.framework/Versions/3.13/lib/python3.13/inspect.py'>
      msg = 'mariadb-dump not found in PATH! This is required to take a backup.'
      out = {'message': 'mariadb-dump not found in PATH! This is required to take a backup.', 'title': 'Message', 'indicator': 'red', 'raise_exception': 1, '__frappe_exc_id': 'ec81987752a4992bd6a3e2e15384ec33ddf5471d0287a20d8664c327'}
      raise_exception = <class 'frappe.exceptions.ExecutableNotFound'>
frappe.exceptions.ExecutableNotFound: mariadb-dump not found in PATH! This is required to take a backup.
Backup failed for Site learning.test. Database or site_config.json may be corrupted
Traceback with variables (most recent call last):
  File "apps/frappe/frappe/commands/site.py", line 865, in backup
    odb = scheduled_backup(
      context = CliCtxObj(sites=['learning.test'], force=False, profile=False, verbose=True)
      with_files = False
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_backup_conf = False
      verbose = True
      compress = False
      include = ''
      exclude = ''
      old_backup_metadata = False
      scheduled_backup = <function scheduled_backup at 0x107413560>
      exit_code = 0
      rollback_callback = None
      site = 'learning.test'
  File "apps/frappe/frappe/utils/backups.py", line 589, in scheduled_backup
    return new_backup(
      older_than = 6
      ignore_files = True
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_conf = False
      include_doctypes = ''
      exclude_doctypes = ''
      compress = False
      force = True
      verbose = True
      old_backup_metadata = False
      rollback_callback = <frappe.utils.CallbackManager object at 0x1075e9c90>
  File "apps/frappe/frappe/utils/backups.py", line 647, in new_backup
    odb.get_backup(older_than, ignore_files, force=force)
      older_than = 6
      ignore_files = True
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_conf = False
      include_doctypes = ''
      exclude_doctypes = ''
      compress = False
      force = True
      verbose = True
      old_backup_metadata = False
      rollback_callback = <frappe.utils.CallbackManager object at 0x1075e9c90>
      odb = <frappe.utils.backups.BackupGenerator object at 0x1076002f0>
  File "apps/frappe/frappe/utils/backups.py", line 191, in get_backup
    self.delete_if_step_fails(self.take_dump, self.backup_path_db)
      self = <frappe.utils.backups.BackupGenerator object at 0x1076002f0>
      older_than = 6
      ignore_files = True
      force = True
      last_db = False
      last_file = False
      last_private_file = False
      site_config_backup_path = False
  File "apps/frappe/frappe/utils/backups.py", line 528, in delete_if_step_fails
    raise e
      self = <frappe.utils.backups.BackupGenerator object at 0x1076002f0>
      step = <bound method BackupGenerator.take_dump of <frappe.utils.backups.BackupGenerator object at 0x1076002f0>>
      paths = ('./learning.test/private/backups/20250623_033023-learning_test-database.sql.gz',)
      path = './learning.test/private/backups/20250623_033023-learning_test-database.sql.gz'
  File "apps/frappe/frappe/utils/backups.py", line 523, in delete_if_step_fails
    step()
      self = <frappe.utils.backups.BackupGenerator object at 0x1076002f0>
      step = <bound method BackupGenerator.take_dump of <frappe.utils.backups.BackupGenerator object at 0x1076002f0>>
      paths = ('./learning.test/private/backups/20250623_033023-learning_test-database.sql.gz',)
      path = './learning.test/private/backups/20250623_033023-learning_test-database.sql.gz'
  File "apps/frappe/frappe/utils/backups.py", line 465, in take_dump
    frappe.throw(
      self = <frappe.utils.backups.BackupGenerator object at 0x1076002f0>
      frappe = <module 'frappe' from 'apps/frappe/frappe/__init__.py'>
      shlex = <module 'shlex' from '/opt/homebrew/Cellar/python@3.13/3.13.5/Frameworks/Python.framework/Versions/3.13/lib/python3.13/shlex.py'>
      get_app_branch = <function get_app_branch at 0x1076059e0>
      gzip_exc = '/usr/bin/gzip'
      database_header_content = ['begin frappe metadata', '[frappe]', 'version = 16.0.0-dev', 'branch = develop', 'end frappe metadata', '']
      generated_header = '-- begin frappe metadata\n-- [frappe]\n-- version = 16.0.0-dev\n-- branch = develop\n-- end frappe metadata\n-- \n'
      f = <_io.TextIOWrapper name='./learning.test/private/backups/20250623_033023-learning_test-database.sql.gz' encoding='UTF-8'>
      cmd = []
      extra = []
      get_command = <function get_command at 0x107481260>
      bin = None
      args = ['--user=_e1faab4bbb015fc1', '--host=127.0.0.1', '--port=3306', '--password=hEEDuC879iaZlv31', '--single-transaction', '--quick', '--lock-tables=false', '_e1faab4bbb015fc1']
      bin_name = 'mariadb-dump'
  File "apps/frappe/frappe/utils/messages.py", line 145, in throw
    msgprint(
      msg = 'mariadb-dump not found in PATH! This is required to take a backup.'
      exc = <class 'frappe.exceptions.ExecutableNotFound'>
      title = None
      is_minimizable = False
      wide = False
      as_list = False
      primary_action = None
  File "apps/frappe/frappe/utils/messages.py", line 106, in msgprint
    _raise_exception()
      msg = 'mariadb-dump not found in PATH! This is required to take a backup.'
      title = None
      raise_exception = <class 'frappe.exceptions.ExecutableNotFound'>
      as_table = False
      as_list = False
      indicator = 'red'
      alert = False
      primary_action = None
      is_minimizable = False
      wide = False
      realtime = False
      _raise_exception = <function msgprint.<locals>._raise_exception at 0x107604680>
      inspect = <module 'inspect' from '/opt/homebrew/Cellar/python@3.13/3.13.5/Frameworks/Python.framework/Versions/3.13/lib/python3.13/inspect.py'>
      out = {'message': 'mariadb-dump not found in PATH! This is required to take a backup.', 'title': 'Message', 'indicator': 'red', 'raise_exception': 1, '__frappe_exc_id': '8b0e88ffb7687f4105c8c7fda24e139abcea690728378ceefe5c6569'}
  File "apps/frappe/frappe/utils/messages.py", line 57, in _raise_exception
    raise exc
      exc = ExecutableNotFound('mariadb-dump not found in PATH! This is required to take a backup.')
      inspect = <module 'inspect' from '/opt/homebrew/Cellar/python@3.13/3.13.5/Frameworks/Python.framework/Versions/3.13/lib/python3.13/inspect.py'>
      msg = 'mariadb-dump not found in PATH! This is required to take a backup.'
      out = {'message': 'mariadb-dump not found in PATH! This is required to take a backup.', 'title': 'Message', 'indicator': 'red', 'raise_exception': 1, '__frappe_exc_id': '8b0e88ffb7687f4105c8c7fda24e139abcea690728378ceefe5c6569'}
      raise_exception = <class 'frappe.exceptions.ExecutableNotFound'>
frappe.exceptions.ExecutableNotFound: mariadb-dump not found in PATH! This is required to take a backup.
Backup failed for Site learning.test. Database or site_config.json may be corrupted
Traceback with variables (most recent call last):
  File "apps/frappe/frappe/commands/site.py", line 843, in backup
    odb = scheduled_backup(
      context = {'sites': ['learning.test'], 'force': False, 'verbose': True, 'profile': False}
      with_files = False
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_backup_conf = False
      verbose = True
      compress = False
      include = ''
      exclude = ''
      old_backup_metadata = False
      scheduled_backup = <function scheduled_backup at 0x101e82660>
      exit_code = 0
      rollback_callback = None
      site = 'learning.test'
  File "apps/frappe/frappe/utils/backups.py", line 568, in scheduled_backup
    return new_backup(
      older_than = 6
      ignore_files = True
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_conf = False
      include_doctypes = ''
      exclude_doctypes = ''
      compress = False
      force = True
      verbose = True
      old_backup_metadata = False
      rollback_callback = <frappe.utils.CallbackManager object at 0x102b46440>
  File "apps/frappe/frappe/utils/backups.py", line 626, in new_backup
    odb.get_backup(older_than, ignore_files, force=force)
      older_than = 6
      ignore_files = True
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_conf = False
      include_doctypes = ''
      exclude_doctypes = ''
      compress = False
      force = True
      verbose = True
      old_backup_metadata = False
      rollback_callback = <frappe.utils.CallbackManager object at 0x102b46440>
      odb = <frappe.utils.backups.BackupGenerator object at 0x102a912d0>
  File "apps/frappe/frappe/utils/backups.py", line 195, in get_backup
    self.delete_if_step_fails(self.take_dump, self.backup_path_db)
      self = <frappe.utils.backups.BackupGenerator object at 0x102a912d0>
      older_than = 6
      ignore_files = True
      force = True
      last_db = False
      last_file = False
      last_private_file = False
      site_config_backup_path = False
  File "apps/frappe/frappe/utils/backups.py", line 520, in delete_if_step_fails
    raise e
      self = <frappe.utils.backups.BackupGenerator object at 0x102a912d0>
      step = <bound method BackupGenerator.take_dump of <frappe.utils.backups.BackupGenerator object at 0x102a912d0>>
      paths = ('./learning.test/private/backups/20250624_033721-learning_test-database.sql.gz',)
      path = './learning.test/private/backups/20250624_033721-learning_test-database.sql.gz'
  File "apps/frappe/frappe/utils/backups.py", line 515, in delete_if_step_fails
    step()
      self = <frappe.utils.backups.BackupGenerator object at 0x102a912d0>
      step = <bound method BackupGenerator.take_dump of <frappe.utils.backups.BackupGenerator object at 0x102a912d0>>
      paths = ('./learning.test/private/backups/20250624_033721-learning_test-database.sql.gz',)
      path = './learning.test/private/backups/20250624_033721-learning_test-database.sql.gz'
  File "apps/frappe/frappe/utils/backups.py", line 457, in take_dump
    frappe.throw(
      self = <frappe.utils.backups.BackupGenerator object at 0x102a912d0>
      shlex = <module 'shlex' from '/Users/huzaifa/.pyenv/versions/3.11.4/lib/python3.11/shlex.py'>
      frappe = <module 'frappe' from 'apps/frappe/frappe/__init__.py'>
      get_app_branch = <function get_app_branch at 0x1014bfe20>
      gzip_exc = '/usr/bin/gzip'
      database_header_content = ['begin frappe metadata', '[frappe]', 'version = 15.71.0', 'branch = version-15', 'end frappe metadata', '']
      generated_header = '-- begin frappe metadata\n-- [frappe]\n-- version = 15.71.0\n-- branch = version-15\n-- end frappe metadata\n-- \n'
      f = <_io.TextIOWrapper name='./learning.test/private/backups/20250624_033721-learning_test-database.sql.gz' encoding='UTF-8'>
      cmd = []
      extra = []
      get_command = <function get_command at 0x102999a80>
      bin = None
      args = ['--user=_e1faab4bbb015fc1', '--host=127.0.0.1', '--port=3306', '--password=hEEDuC879iaZlv31', '--single-transaction', '--quick', '--lock-tables=false', '_e1faab4bbb015fc1']
      bin_name = 'mariadb-dump'
  File "apps/frappe/frappe/__init__.py", line 609, in throw
    msgprint(
      msg = 'mariadb-dump not found in PATH! This is required to take a backup.'
      exc = <class 'frappe.exceptions.ExecutableNotFound'>
      title = None
      is_minimizable = False
      wide = False
      as_list = False
      primary_action = None
  File "apps/frappe/frappe/__init__.py", line 574, in msgprint
    _raise_exception()
      msg = 'mariadb-dump not found in PATH! This is required to take a backup.'
      title = None
      raise_exception = <class 'frappe.exceptions.ExecutableNotFound'>
      as_table = False
      as_list = False
      indicator = 'red'
      alert = False
      primary_action = None
      is_minimizable = False
      wide = False
      realtime = False
      sys = <module 'sys' (built-in)>
      _raise_exception = <function msgprint.<locals>._raise_exception at 0x10145fd80>
      inspect = <module 'inspect' from '/Users/huzaifa/.pyenv/versions/3.11.4/lib/python3.11/inspect.py'>
      out = {'message': 'mariadb-dump not found in PATH! This is required to take a backup.', 'title': 'Message', 'indicator': 'red', 'raise_exception': 1, '__frappe_exc_id': '83d4599c765544399bd33502cd61d99bd9570539c9d8adbc5c9cdec4'}
  File "apps/frappe/frappe/__init__.py", line 525, in _raise_exception
    raise exc
      exc = ExecutableNotFound('mariadb-dump not found in PATH! This is required to take a backup.')
      inspect = <module 'inspect' from '/Users/huzaifa/.pyenv/versions/3.11.4/lib/python3.11/inspect.py'>
      msg = 'mariadb-dump not found in PATH! This is required to take a backup.'
      out = {'message': 'mariadb-dump not found in PATH! This is required to take a backup.', 'title': 'Message', 'indicator': 'red', 'raise_exception': 1, '__frappe_exc_id': '83d4599c765544399bd33502cd61d99bd9570539c9d8adbc5c9cdec4'}
      raise_exception = <class 'frappe.exceptions.ExecutableNotFound'>
frappe.exceptions.ExecutableNotFound: mariadb-dump not found in PATH! This is required to take a backup.
Backup failed for Site learning.test. Database or site_config.json may be corrupted
Traceback with variables (most recent call last):
  File "apps/frappe/frappe/commands/site.py", line 843, in backup
    odb = scheduled_backup(
      context = {'sites': ['learning.test'], 'force': False, 'verbose': True, 'profile': False}
      with_files = False
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_backup_conf = False
      verbose = True
      compress = False
      include = ''
      exclude = ''
      old_backup_metadata = False
      scheduled_backup = <function scheduled_backup at 0x1047ee660>
      exit_code = 0
      rollback_callback = None
      site = 'learning.test'
  File "apps/frappe/frappe/utils/backups.py", line 568, in scheduled_backup
    return new_backup(
      older_than = 6
      ignore_files = True
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_conf = False
      include_doctypes = ''
      exclude_doctypes = ''
      compress = False
      force = True
      verbose = True
      old_backup_metadata = False
      rollback_callback = <frappe.utils.CallbackManager object at 0x105282440>
  File "apps/frappe/frappe/utils/backups.py", line 626, in new_backup
    odb.get_backup(older_than, ignore_files, force=force)
      older_than = 6
      ignore_files = True
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_conf = False
      include_doctypes = ''
      exclude_doctypes = ''
      compress = False
      force = True
      verbose = True
      old_backup_metadata = False
      rollback_callback = <frappe.utils.CallbackManager object at 0x105282440>
      odb = <frappe.utils.backups.BackupGenerator object at 0x1051cd310>
  File "apps/frappe/frappe/utils/backups.py", line 195, in get_backup
    self.delete_if_step_fails(self.take_dump, self.backup_path_db)
      self = <frappe.utils.backups.BackupGenerator object at 0x1051cd310>
      older_than = 6
      ignore_files = True
      force = True
      last_db = False
      last_file = False
      last_private_file = False
      site_config_backup_path = False
  File "apps/frappe/frappe/utils/backups.py", line 520, in delete_if_step_fails
    raise e
      self = <frappe.utils.backups.BackupGenerator object at 0x1051cd310>
      step = <bound method BackupGenerator.take_dump of <frappe.utils.backups.BackupGenerator object at 0x1051cd310>>
      paths = ('./learning.test/private/backups/20250628_033001-learning_test-database.sql.gz',)
      path = './learning.test/private/backups/20250628_033001-learning_test-database.sql.gz'
  File "apps/frappe/frappe/utils/backups.py", line 515, in delete_if_step_fails
    step()
      self = <frappe.utils.backups.BackupGenerator object at 0x1051cd310>
      step = <bound method BackupGenerator.take_dump of <frappe.utils.backups.BackupGenerator object at 0x1051cd310>>
      paths = ('./learning.test/private/backups/20250628_033001-learning_test-database.sql.gz',)
      path = './learning.test/private/backups/20250628_033001-learning_test-database.sql.gz'
  File "apps/frappe/frappe/utils/backups.py", line 457, in take_dump
    frappe.throw(
      self = <frappe.utils.backups.BackupGenerator object at 0x1051cd310>
      shlex = <module 'shlex' from '/Users/huzaifa/.pyenv/versions/3.11.4/lib/python3.11/shlex.py'>
      frappe = <module 'frappe' from 'apps/frappe/frappe/__init__.py'>
      get_app_branch = <function get_app_branch at 0x103f63e20>
      gzip_exc = '/usr/bin/gzip'
      database_header_content = ['begin frappe metadata', '[frappe]', 'version = 15.71.0', 'branch = version-15', 'end frappe metadata', '']
      generated_header = '-- begin frappe metadata\n-- [frappe]\n-- version = 15.71.0\n-- branch = version-15\n-- end frappe metadata\n-- \n'
      f = <_io.TextIOWrapper name='./learning.test/private/backups/20250628_033001-learning_test-database.sql.gz' encoding='UTF-8'>
      cmd = []
      extra = []
      get_command = <function get_command at 0x1050d5a80>
      bin = None
      args = ['--user=_e1faab4bbb015fc1', '--host=127.0.0.1', '--port=3306', '--password=hEEDuC879iaZlv31', '--single-transaction', '--quick', '--lock-tables=false', '_e1faab4bbb015fc1']
      bin_name = 'mariadb-dump'
  File "apps/frappe/frappe/__init__.py", line 609, in throw
    msgprint(
      msg = 'mariadb-dump not found in PATH! This is required to take a backup.'
      exc = <class 'frappe.exceptions.ExecutableNotFound'>
      title = None
      is_minimizable = False
      wide = False
      as_list = False
      primary_action = None
  File "apps/frappe/frappe/__init__.py", line 574, in msgprint
    _raise_exception()
      msg = 'mariadb-dump not found in PATH! This is required to take a backup.'
      title = None
      raise_exception = <class 'frappe.exceptions.ExecutableNotFound'>
      as_table = False
      as_list = False
      indicator = 'red'
      alert = False
      primary_action = None
      is_minimizable = False
      wide = False
      realtime = False
      sys = <module 'sys' (built-in)>
      _raise_exception = <function msgprint.<locals>._raise_exception at 0x103f03d80>
      inspect = <module 'inspect' from '/Users/huzaifa/.pyenv/versions/3.11.4/lib/python3.11/inspect.py'>
      out = {'message': 'mariadb-dump not found in PATH! This is required to take a backup.', 'title': 'Message', 'indicator': 'red', 'raise_exception': 1, '__frappe_exc_id': '6b110467c877289cedda47e7bbbb193c583d55101848db672699d525'}
  File "apps/frappe/frappe/__init__.py", line 525, in _raise_exception
    raise exc
      exc = ExecutableNotFound('mariadb-dump not found in PATH! This is required to take a backup.')
      inspect = <module 'inspect' from '/Users/huzaifa/.pyenv/versions/3.11.4/lib/python3.11/inspect.py'>
      msg = 'mariadb-dump not found in PATH! This is required to take a backup.'
      out = {'message': 'mariadb-dump not found in PATH! This is required to take a backup.', 'title': 'Message', 'indicator': 'red', 'raise_exception': 1, '__frappe_exc_id': '6b110467c877289cedda47e7bbbb193c583d55101848db672699d525'}
      raise_exception = <class 'frappe.exceptions.ExecutableNotFound'>
frappe.exceptions.ExecutableNotFound: mariadb-dump not found in PATH! This is required to take a backup.
Backup failed for Site learning.test. Database or site_config.json may be corrupted
Traceback with variables (most recent call last):
  File "apps/frappe/frappe/commands/site.py", line 843, in backup
    odb = scheduled_backup(
      context = {'sites': ['learning.test'], 'force': False, 'verbose': True, 'profile': False}
      with_files = False
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_backup_conf = False
      verbose = True
      compress = False
      include = ''
      exclude = ''
      old_backup_metadata = False
      scheduled_backup = <function scheduled_backup at 0x102cf6660>
      exit_code = 0
      rollback_callback = None
      site = 'learning.test'
  File "apps/frappe/frappe/utils/backups.py", line 568, in scheduled_backup
    return new_backup(
      older_than = 6
      ignore_files = True
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_conf = False
      include_doctypes = ''
      exclude_doctypes = ''
      compress = False
      force = True
      verbose = True
      old_backup_metadata = False
      rollback_callback = <frappe.utils.CallbackManager object at 0x10378a440>
  File "apps/frappe/frappe/utils/backups.py", line 626, in new_backup
    odb.get_backup(older_than, ignore_files, force=force)
      older_than = 6
      ignore_files = True
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_conf = False
      include_doctypes = ''
      exclude_doctypes = ''
      compress = False
      force = True
      verbose = True
      old_backup_metadata = False
      rollback_callback = <frappe.utils.CallbackManager object at 0x10378a440>
      odb = <frappe.utils.backups.BackupGenerator object at 0x1036d52d0>
  File "apps/frappe/frappe/utils/backups.py", line 195, in get_backup
    self.delete_if_step_fails(self.take_dump, self.backup_path_db)
      self = <frappe.utils.backups.BackupGenerator object at 0x1036d52d0>
      older_than = 6
      ignore_files = True
      force = True
      last_db = False
      last_file = False
      last_private_file = False
      site_config_backup_path = False
  File "apps/frappe/frappe/utils/backups.py", line 520, in delete_if_step_fails
    raise e
      self = <frappe.utils.backups.BackupGenerator object at 0x1036d52d0>
      step = <bound method BackupGenerator.take_dump of <frappe.utils.backups.BackupGenerator object at 0x1036d52d0>>
      paths = ('./learning.test/private/backups/20250629_033001-learning_test-database.sql.gz',)
      path = './learning.test/private/backups/20250629_033001-learning_test-database.sql.gz'
  File "apps/frappe/frappe/utils/backups.py", line 515, in delete_if_step_fails
    step()
      self = <frappe.utils.backups.BackupGenerator object at 0x1036d52d0>
      step = <bound method BackupGenerator.take_dump of <frappe.utils.backups.BackupGenerator object at 0x1036d52d0>>
      paths = ('./learning.test/private/backups/20250629_033001-learning_test-database.sql.gz',)
      path = './learning.test/private/backups/20250629_033001-learning_test-database.sql.gz'
  File "apps/frappe/frappe/utils/backups.py", line 457, in take_dump
    frappe.throw(
      self = <frappe.utils.backups.BackupGenerator object at 0x1036d52d0>
      shlex = <module 'shlex' from '/Users/huzaifa/.pyenv/versions/3.11.4/lib/python3.11/shlex.py'>
      frappe = <module 'frappe' from 'apps/frappe/frappe/__init__.py'>
      get_app_branch = <function get_app_branch at 0x10246be20>
      gzip_exc = '/usr/bin/gzip'
      database_header_content = ['begin frappe metadata', '[frappe]', 'version = 15.71.0', 'branch = version-15', 'end frappe metadata', '']
      generated_header = '-- begin frappe metadata\n-- [frappe]\n-- version = 15.71.0\n-- branch = version-15\n-- end frappe metadata\n-- \n'
      f = <_io.TextIOWrapper name='./learning.test/private/backups/20250629_033001-learning_test-database.sql.gz' encoding='UTF-8'>
      cmd = []
      extra = []
      get_command = <function get_command at 0x1035dda80>
      bin = None
      args = ['--user=_e1faab4bbb015fc1', '--host=127.0.0.1', '--port=3306', '--password=hEEDuC879iaZlv31', '--single-transaction', '--quick', '--lock-tables=false', '_e1faab4bbb015fc1']
      bin_name = 'mariadb-dump'
  File "apps/frappe/frappe/__init__.py", line 609, in throw
    msgprint(
      msg = 'mariadb-dump not found in PATH! This is required to take a backup.'
      exc = <class 'frappe.exceptions.ExecutableNotFound'>
      title = None
      is_minimizable = False
      wide = False
      as_list = False
      primary_action = None
  File "apps/frappe/frappe/__init__.py", line 574, in msgprint
    _raise_exception()
      msg = 'mariadb-dump not found in PATH! This is required to take a backup.'
      title = None
      raise_exception = <class 'frappe.exceptions.ExecutableNotFound'>
      as_table = False
      as_list = False
      indicator = 'red'
      alert = False
      primary_action = None
      is_minimizable = False
      wide = False
      realtime = False
      sys = <module 'sys' (built-in)>
      _raise_exception = <function msgprint.<locals>._raise_exception at 0x10240bd80>
      inspect = <module 'inspect' from '/Users/huzaifa/.pyenv/versions/3.11.4/lib/python3.11/inspect.py'>
      out = {'message': 'mariadb-dump not found in PATH! This is required to take a backup.', 'title': 'Message', 'indicator': 'red', 'raise_exception': 1, '__frappe_exc_id': '37a045c4d311d40a07b28d2eedb6c26416a14cfca441f4b5017b98f3'}
  File "apps/frappe/frappe/__init__.py", line 525, in _raise_exception
    raise exc
      exc = ExecutableNotFound('mariadb-dump not found in PATH! This is required to take a backup.')
      inspect = <module 'inspect' from '/Users/huzaifa/.pyenv/versions/3.11.4/lib/python3.11/inspect.py'>
      msg = 'mariadb-dump not found in PATH! This is required to take a backup.'
      out = {'message': 'mariadb-dump not found in PATH! This is required to take a backup.', 'title': 'Message', 'indicator': 'red', 'raise_exception': 1, '__frappe_exc_id': '37a045c4d311d40a07b28d2eedb6c26416a14cfca441f4b5017b98f3'}
      raise_exception = <class 'frappe.exceptions.ExecutableNotFound'>
frappe.exceptions.ExecutableNotFound: mariadb-dump not found in PATH! This is required to take a backup.
Backup failed for Site learning.test. Database or site_config.json may be corrupted
Traceback with variables (most recent call last):
  File "apps/frappe/frappe/commands/site.py", line 843, in backup
    odb = scheduled_backup(
      context = {'sites': ['learning.test'], 'force': False, 'verbose': True, 'profile': False}
      with_files = False
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_backup_conf = False
      verbose = True
      compress = False
      include = ''
      exclude = ''
      old_backup_metadata = False
      scheduled_backup = <function scheduled_backup at 0x1064ca660>
      exit_code = 0
      rollback_callback = None
      site = 'learning.test'
  File "apps/frappe/frappe/utils/backups.py", line 568, in scheduled_backup
    return new_backup(
      older_than = 6
      ignore_files = True
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_conf = False
      include_doctypes = ''
      exclude_doctypes = ''
      compress = False
      force = True
      verbose = True
      old_backup_metadata = False
      rollback_callback = <frappe.utils.CallbackManager object at 0x106f5e740>
  File "apps/frappe/frappe/utils/backups.py", line 626, in new_backup
    odb.get_backup(older_than, ignore_files, force=force)
      older_than = 6
      ignore_files = True
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_conf = False
      include_doctypes = ''
      exclude_doctypes = ''
      compress = False
      force = True
      verbose = True
      old_backup_metadata = False
      rollback_callback = <frappe.utils.CallbackManager object at 0x106f5e740>
      odb = <frappe.utils.backups.BackupGenerator object at 0x106ea92d0>
  File "apps/frappe/frappe/utils/backups.py", line 195, in get_backup
    self.delete_if_step_fails(self.take_dump, self.backup_path_db)
      self = <frappe.utils.backups.BackupGenerator object at 0x106ea92d0>
      older_than = 6
      ignore_files = True
      force = True
      last_db = False
      last_file = False
      last_private_file = False
      site_config_backup_path = False
  File "apps/frappe/frappe/utils/backups.py", line 520, in delete_if_step_fails
    raise e
      self = <frappe.utils.backups.BackupGenerator object at 0x106ea92d0>
      step = <bound method BackupGenerator.take_dump of <frappe.utils.backups.BackupGenerator object at 0x106ea92d0>>
      paths = ('./learning.test/private/backups/20250630_093002-learning_test-database.sql.gz',)
      path = './learning.test/private/backups/20250630_093002-learning_test-database.sql.gz'
  File "apps/frappe/frappe/utils/backups.py", line 515, in delete_if_step_fails
    step()
      self = <frappe.utils.backups.BackupGenerator object at 0x106ea92d0>
      step = <bound method BackupGenerator.take_dump of <frappe.utils.backups.BackupGenerator object at 0x106ea92d0>>
      paths = ('./learning.test/private/backups/20250630_093002-learning_test-database.sql.gz',)
      path = './learning.test/private/backups/20250630_093002-learning_test-database.sql.gz'
  File "apps/frappe/frappe/utils/backups.py", line 457, in take_dump
    frappe.throw(
      self = <frappe.utils.backups.BackupGenerator object at 0x106ea92d0>
      shlex = <module 'shlex' from '/Users/huzaifa/.pyenv/versions/3.11.4/lib/python3.11/shlex.py'>
      frappe = <module 'frappe' from 'apps/frappe/frappe/__init__.py'>
      get_app_branch = <function get_app_branch at 0x1088005e0>
      gzip_exc = '/usr/bin/gzip'
      database_header_content = ['begin frappe metadata', '[frappe]', 'version = 15.71.0', 'branch = version-15', 'end frappe metadata', '']
      generated_header = '-- begin frappe metadata\n-- [frappe]\n-- version = 15.71.0\n-- branch = version-15\n-- end frappe metadata\n-- \n'
      f = <_io.TextIOWrapper name='./learning.test/private/backups/20250630_093002-learning_test-database.sql.gz' encoding='UTF-8'>
      cmd = []
      extra = []
      get_command = <function get_command at 0x106db1a80>
      bin = None
      args = ['--user=_e1faab4bbb015fc1', '--host=127.0.0.1', '--port=3306', '--password=hEEDuC879iaZlv31', '--single-transaction', '--quick', '--lock-tables=false', '_e1faab4bbb015fc1']
      bin_name = 'mariadb-dump'
  File "apps/frappe/frappe/__init__.py", line 609, in throw
    msgprint(
      msg = 'mariadb-dump not found in PATH! This is required to take a backup.'
      exc = <class 'frappe.exceptions.ExecutableNotFound'>
      title = None
      is_minimizable = False
      wide = False
      as_list = False
      primary_action = None
  File "apps/frappe/frappe/__init__.py", line 574, in msgprint
    _raise_exception()
      msg = 'mariadb-dump not found in PATH! This is required to take a backup.'
      title = None
      raise_exception = <class 'frappe.exceptions.ExecutableNotFound'>
      as_table = False
      as_list = False
      indicator = 'red'
      alert = False
      primary_action = None
      is_minimizable = False
      wide = False
      realtime = False
      sys = <module 'sys' (built-in)>
      _raise_exception = <function msgprint.<locals>._raise_exception at 0x108a79da0>
      inspect = <module 'inspect' from '/Users/huzaifa/.pyenv/versions/3.11.4/lib/python3.11/inspect.py'>
      out = {'message': 'mariadb-dump not found in PATH! This is required to take a backup.', 'title': 'Message', 'indicator': 'red', 'raise_exception': 1, '__frappe_exc_id': '720862ba02f8b0edebf98c4368de68b280a41908f14246f08b991aa3'}
  File "apps/frappe/frappe/__init__.py", line 525, in _raise_exception
    raise exc
      exc = ExecutableNotFound('mariadb-dump not found in PATH! This is required to take a backup.')
      inspect = <module 'inspect' from '/Users/huzaifa/.pyenv/versions/3.11.4/lib/python3.11/inspect.py'>
      msg = 'mariadb-dump not found in PATH! This is required to take a backup.'
      out = {'message': 'mariadb-dump not found in PATH! This is required to take a backup.', 'title': 'Message', 'indicator': 'red', 'raise_exception': 1, '__frappe_exc_id': '720862ba02f8b0edebf98c4368de68b280a41908f14246f08b991aa3'}
      raise_exception = <class 'frappe.exceptions.ExecutableNotFound'>
frappe.exceptions.ExecutableNotFound: mariadb-dump not found in PATH! This is required to take a backup.
Backup failed for Site learning.test. Database or site_config.json may be corrupted
Traceback with variables (most recent call last):
  File "apps/frappe/frappe/commands/site.py", line 843, in backup
    odb = scheduled_backup(
      context = {'sites': ['learning.test'], 'force': False, 'verbose': True, 'profile': False}
      with_files = False
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_backup_conf = False
      verbose = True
      compress = False
      include = ''
      exclude = ''
      old_backup_metadata = False
      scheduled_backup = <function scheduled_backup at 0x102d82660>
      exit_code = 0
      rollback_callback = None
      site = 'learning.test'
  File "apps/frappe/frappe/utils/backups.py", line 568, in scheduled_backup
    return new_backup(
      older_than = 6
      ignore_files = True
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_conf = False
      include_doctypes = ''
      exclude_doctypes = ''
      compress = False
      force = True
      verbose = True
      old_backup_metadata = False
      rollback_callback = <frappe.utils.CallbackManager object at 0x103a46740>
  File "apps/frappe/frappe/utils/backups.py", line 626, in new_backup
    odb.get_backup(older_than, ignore_files, force=force)
      older_than = 6
      ignore_files = True
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_conf = False
      include_doctypes = ''
      exclude_doctypes = ''
      compress = False
      force = True
      verbose = True
      old_backup_metadata = False
      rollback_callback = <frappe.utils.CallbackManager object at 0x103a46740>
      odb = <frappe.utils.backups.BackupGenerator object at 0x1039912d0>
  File "apps/frappe/frappe/utils/backups.py", line 195, in get_backup
    self.delete_if_step_fails(self.take_dump, self.backup_path_db)
      self = <frappe.utils.backups.BackupGenerator object at 0x1039912d0>
      older_than = 6
      ignore_files = True
      force = True
      last_db = False
      last_file = False
      last_private_file = False
      site_config_backup_path = False
  File "apps/frappe/frappe/utils/backups.py", line 520, in delete_if_step_fails
    raise e
      self = <frappe.utils.backups.BackupGenerator object at 0x1039912d0>
      step = <bound method BackupGenerator.take_dump of <frappe.utils.backups.BackupGenerator object at 0x1039912d0>>
      paths = ('./learning.test/private/backups/20250705_093003-learning_test-database.sql.gz',)
      path = './learning.test/private/backups/20250705_093003-learning_test-database.sql.gz'
  File "apps/frappe/frappe/utils/backups.py", line 515, in delete_if_step_fails
    step()
      self = <frappe.utils.backups.BackupGenerator object at 0x1039912d0>
      step = <bound method BackupGenerator.take_dump of <frappe.utils.backups.BackupGenerator object at 0x1039912d0>>
      paths = ('./learning.test/private/backups/20250705_093003-learning_test-database.sql.gz',)
      path = './learning.test/private/backups/20250705_093003-learning_test-database.sql.gz'
  File "apps/frappe/frappe/utils/backups.py", line 457, in take_dump
    frappe.throw(
      self = <frappe.utils.backups.BackupGenerator object at 0x1039912d0>
      shlex = <module 'shlex' from '/Users/huzaifa/.pyenv/versions/3.11.4/lib/python3.11/shlex.py'>
      frappe = <module 'frappe' from 'apps/frappe/frappe/__init__.py'>
      get_app_branch = <function get_app_branch at 0x1053e05e0>
      gzip_exc = '/usr/bin/gzip'
      database_header_content = ['begin frappe metadata', '[frappe]', 'version = 15.71.0', 'branch = version-15', 'end frappe metadata', '']
      generated_header = '-- begin frappe metadata\n-- [frappe]\n-- version = 15.71.0\n-- branch = version-15\n-- end frappe metadata\n-- \n'
      f = <_io.TextIOWrapper name='./learning.test/private/backups/20250705_093003-learning_test-database.sql.gz' encoding='UTF-8'>
      cmd = []
      extra = []
      get_command = <function get_command at 0x103899a80>
      bin = None
      args = ['--user=_e1faab4bbb015fc1', '--host=127.0.0.1', '--port=3306', '--password=hEEDuC879iaZlv31', '--single-transaction', '--quick', '--lock-tables=false', '_e1faab4bbb015fc1']
      bin_name = 'mariadb-dump'
  File "apps/frappe/frappe/__init__.py", line 609, in throw
    msgprint(
      msg = 'mariadb-dump not found in PATH! This is required to take a backup.'
      exc = <class 'frappe.exceptions.ExecutableNotFound'>
      title = None
      is_minimizable = False
      wide = False
      as_list = False
      primary_action = None
  File "apps/frappe/frappe/__init__.py", line 574, in msgprint
    _raise_exception()
      msg = 'mariadb-dump not found in PATH! This is required to take a backup.'
      title = None
      raise_exception = <class 'frappe.exceptions.ExecutableNotFound'>
      as_table = False
      as_list = False
      indicator = 'red'
      alert = False
      primary_action = None
      is_minimizable = False
      wide = False
      realtime = False
      sys = <module 'sys' (built-in)>
      _raise_exception = <function msgprint.<locals>._raise_exception at 0x105655da0>
      inspect = <module 'inspect' from '/Users/huzaifa/.pyenv/versions/3.11.4/lib/python3.11/inspect.py'>
      out = {'message': 'mariadb-dump not found in PATH! This is required to take a backup.', 'title': 'Message', 'indicator': 'red', 'raise_exception': 1, '__frappe_exc_id': '5d24c28e9e38dd6ead374ae4c9831b486256af7142ebad21b50ee977'}
  File "apps/frappe/frappe/__init__.py", line 525, in _raise_exception
    raise exc
      exc = ExecutableNotFound('mariadb-dump not found in PATH! This is required to take a backup.')
      inspect = <module 'inspect' from '/Users/huzaifa/.pyenv/versions/3.11.4/lib/python3.11/inspect.py'>
      msg = 'mariadb-dump not found in PATH! This is required to take a backup.'
      out = {'message': 'mariadb-dump not found in PATH! This is required to take a backup.', 'title': 'Message', 'indicator': 'red', 'raise_exception': 1, '__frappe_exc_id': '5d24c28e9e38dd6ead374ae4c9831b486256af7142ebad21b50ee977'}
      raise_exception = <class 'frappe.exceptions.ExecutableNotFound'>
frappe.exceptions.ExecutableNotFound: mariadb-dump not found in PATH! This is required to take a backup.
Backup failed for Site learning.test. Database or site_config.json may be corrupted
Traceback with variables (most recent call last):
  File "apps/frappe/frappe/commands/site.py", line 843, in backup
    odb = scheduled_backup(
      context = {'sites': ['learning.test'], 'force': False, 'verbose': True, 'profile': False}
      with_files = False
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_backup_conf = False
      verbose = True
      compress = False
      include = ''
      exclude = ''
      old_backup_metadata = False
      scheduled_backup = <function scheduled_backup at 0x1049b6660>
      exit_code = 0
      rollback_callback = None
      site = 'learning.test'
  File "apps/frappe/frappe/utils/backups.py", line 568, in scheduled_backup
    return new_backup(
      older_than = 6
      ignore_files = True
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_conf = False
      include_doctypes = ''
      exclude_doctypes = ''
      compress = False
      force = True
      verbose = True
      old_backup_metadata = False
      rollback_callback = <frappe.utils.CallbackManager object at 0x10544a740>
  File "apps/frappe/frappe/utils/backups.py", line 626, in new_backup
    odb.get_backup(older_than, ignore_files, force=force)
      older_than = 6
      ignore_files = True
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_conf = False
      include_doctypes = ''
      exclude_doctypes = ''
      compress = False
      force = True
      verbose = True
      old_backup_metadata = False
      rollback_callback = <frappe.utils.CallbackManager object at 0x10544a740>
      odb = <frappe.utils.backups.BackupGenerator object at 0x105395310>
  File "apps/frappe/frappe/utils/backups.py", line 195, in get_backup
    self.delete_if_step_fails(self.take_dump, self.backup_path_db)
      self = <frappe.utils.backups.BackupGenerator object at 0x105395310>
      older_than = 6
      ignore_files = True
      force = True
      last_db = False
      last_file = False
      last_private_file = False
      site_config_backup_path = False
  File "apps/frappe/frappe/utils/backups.py", line 520, in delete_if_step_fails
    raise e
      self = <frappe.utils.backups.BackupGenerator object at 0x105395310>
      step = <bound method BackupGenerator.take_dump of <frappe.utils.backups.BackupGenerator object at 0x105395310>>
      paths = ('./learning.test/private/backups/20250706_213002-learning_test-database.sql.gz',)
      path = './learning.test/private/backups/20250706_213002-learning_test-database.sql.gz'
  File "apps/frappe/frappe/utils/backups.py", line 515, in delete_if_step_fails
    step()
      self = <frappe.utils.backups.BackupGenerator object at 0x105395310>
      step = <bound method BackupGenerator.take_dump of <frappe.utils.backups.BackupGenerator object at 0x105395310>>
      paths = ('./learning.test/private/backups/20250706_213002-learning_test-database.sql.gz',)
      path = './learning.test/private/backups/20250706_213002-learning_test-database.sql.gz'
  File "apps/frappe/frappe/utils/backups.py", line 457, in take_dump
    frappe.throw(
      self = <frappe.utils.backups.BackupGenerator object at 0x105395310>
      shlex = <module 'shlex' from '/Users/huzaifa/.pyenv/versions/3.11.4/lib/python3.11/shlex.py'>
      frappe = <module 'frappe' from 'apps/frappe/frappe/__init__.py'>
      get_app_branch = <function get_app_branch at 0x106cf05e0>
      gzip_exc = '/usr/bin/gzip'
      database_header_content = ['begin frappe metadata', '[frappe]', 'version = 15.71.0', 'branch = version-15', 'end frappe metadata', '']
      generated_header = '-- begin frappe metadata\n-- [frappe]\n-- version = 15.71.0\n-- branch = version-15\n-- end frappe metadata\n-- \n'
      f = <_io.TextIOWrapper name='./learning.test/private/backups/20250706_213002-learning_test-database.sql.gz' encoding='UTF-8'>
      cmd = []
      extra = []
      get_command = <function get_command at 0x10529da80>
      bin = None
      args = ['--user=_e1faab4bbb015fc1', '--host=127.0.0.1', '--port=3306', '--password=hEEDuC879iaZlv31', '--single-transaction', '--quick', '--lock-tables=false', '_e1faab4bbb015fc1']
      bin_name = 'mariadb-dump'
  File "apps/frappe/frappe/__init__.py", line 609, in throw
    msgprint(
      msg = 'mariadb-dump not found in PATH! This is required to take a backup.'
      exc = <class 'frappe.exceptions.ExecutableNotFound'>
      title = None
      is_minimizable = False
      wide = False
      as_list = False
      primary_action = None
  File "apps/frappe/frappe/__init__.py", line 574, in msgprint
    _raise_exception()
      msg = 'mariadb-dump not found in PATH! This is required to take a backup.'
      title = None
      raise_exception = <class 'frappe.exceptions.ExecutableNotFound'>
      as_table = False
      as_list = False
      indicator = 'red'
      alert = False
      primary_action = None
      is_minimizable = False
      wide = False
      realtime = False
      sys = <module 'sys' (built-in)>
      _raise_exception = <function msgprint.<locals>._raise_exception at 0x106f65da0>
      inspect = <module 'inspect' from '/Users/huzaifa/.pyenv/versions/3.11.4/lib/python3.11/inspect.py'>
      out = {'message': 'mariadb-dump not found in PATH! This is required to take a backup.', 'title': 'Message', 'indicator': 'red', 'raise_exception': 1, '__frappe_exc_id': '4855c5806431546845ded7ce7d6c7e8c21097a3bc3d692b40a862d86'}
  File "apps/frappe/frappe/__init__.py", line 525, in _raise_exception
    raise exc
      exc = ExecutableNotFound('mariadb-dump not found in PATH! This is required to take a backup.')
      inspect = <module 'inspect' from '/Users/huzaifa/.pyenv/versions/3.11.4/lib/python3.11/inspect.py'>
      msg = 'mariadb-dump not found in PATH! This is required to take a backup.'
      out = {'message': 'mariadb-dump not found in PATH! This is required to take a backup.', 'title': 'Message', 'indicator': 'red', 'raise_exception': 1, '__frappe_exc_id': '4855c5806431546845ded7ce7d6c7e8c21097a3bc3d692b40a862d86'}
      raise_exception = <class 'frappe.exceptions.ExecutableNotFound'>
frappe.exceptions.ExecutableNotFound: mariadb-dump not found in PATH! This is required to take a backup.
Backup failed for Site learning.test. Database or site_config.json may be corrupted
Traceback with variables (most recent call last):
  File "apps/frappe/frappe/commands/site.py", line 843, in backup
    odb = scheduled_backup(
      context = {'sites': ['learning.test'], 'force': False, 'verbose': True, 'profile': False}
      with_files = False
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_backup_conf = False
      verbose = True
      compress = False
      include = ''
      exclude = ''
      old_backup_metadata = False
      scheduled_backup = <function scheduled_backup at 0x106982660>
      exit_code = 0
      rollback_callback = None
      site = 'learning.test'
  File "apps/frappe/frappe/utils/backups.py", line 568, in scheduled_backup
    return new_backup(
      older_than = 6
      ignore_files = True
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_conf = False
      include_doctypes = ''
      exclude_doctypes = ''
      compress = False
      force = True
      verbose = True
      old_backup_metadata = False
      rollback_callback = <frappe.utils.CallbackManager object at 0x10746e740>
  File "apps/frappe/frappe/utils/backups.py", line 626, in new_backup
    odb.get_backup(older_than, ignore_files, force=force)
      older_than = 6
      ignore_files = True
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_conf = False
      include_doctypes = ''
      exclude_doctypes = ''
      compress = False
      force = True
      verbose = True
      old_backup_metadata = False
      rollback_callback = <frappe.utils.CallbackManager object at 0x10746e740>
      odb = <frappe.utils.backups.BackupGenerator object at 0x1073b5050>
  File "apps/frappe/frappe/utils/backups.py", line 195, in get_backup
    self.delete_if_step_fails(self.take_dump, self.backup_path_db)
      self = <frappe.utils.backups.BackupGenerator object at 0x1073b5050>
      older_than = 6
      ignore_files = True
      force = True
      last_db = False
      last_file = False
      last_private_file = False
      site_config_backup_path = False
  File "apps/frappe/frappe/utils/backups.py", line 520, in delete_if_step_fails
    raise e
      self = <frappe.utils.backups.BackupGenerator object at 0x1073b5050>
      step = <bound method BackupGenerator.take_dump of <frappe.utils.backups.BackupGenerator object at 0x1073b5050>>
      paths = ('./learning.test/private/backups/20250707_213001-learning_test-database.sql.gz',)
      path = './learning.test/private/backups/20250707_213001-learning_test-database.sql.gz'
  File "apps/frappe/frappe/utils/backups.py", line 515, in delete_if_step_fails
    step()
      self = <frappe.utils.backups.BackupGenerator object at 0x1073b5050>
      step = <bound method BackupGenerator.take_dump of <frappe.utils.backups.BackupGenerator object at 0x1073b5050>>
      paths = ('./learning.test/private/backups/20250707_213001-learning_test-database.sql.gz',)
      path = './learning.test/private/backups/20250707_213001-learning_test-database.sql.gz'
  File "apps/frappe/frappe/utils/backups.py", line 457, in take_dump
    frappe.throw(
      self = <frappe.utils.backups.BackupGenerator object at 0x1073b5050>
      shlex = <module 'shlex' from '/Users/huzaifa/.pyenv/versions/3.11.4/lib/python3.11/shlex.py'>
      frappe = <module 'frappe' from 'apps/frappe/frappe/__init__.py'>
      get_app_branch = <function get_app_branch at 0x108ed85e0>
      gzip_exc = '/usr/bin/gzip'
      database_header_content = ['begin frappe metadata', '[frappe]', 'version = 15.71.0', 'branch = version-15', 'end frappe metadata', '']
      generated_header = '-- begin frappe metadata\n-- [frappe]\n-- version = 15.71.0\n-- branch = version-15\n-- end frappe metadata\n-- \n'
      f = <_io.TextIOWrapper name='./learning.test/private/backups/20250707_213001-learning_test-database.sql.gz' encoding='UTF-8'>
      cmd = []
      extra = []
      get_command = <function get_command at 0x1072c1a80>
      bin = None
      args = ['--user=_e1faab4bbb015fc1', '--host=127.0.0.1', '--port=3306', '--password=hEEDuC879iaZlv31', '--single-transaction', '--quick', '--lock-tables=false', '_e1faab4bbb015fc1']
      bin_name = 'mariadb-dump'
  File "apps/frappe/frappe/__init__.py", line 609, in throw
    msgprint(
      msg = 'mariadb-dump not found in PATH! This is required to take a backup.'
      exc = <class 'frappe.exceptions.ExecutableNotFound'>
      title = None
      is_minimizable = False
      wide = False
      as_list = False
      primary_action = None
  File "apps/frappe/frappe/__init__.py", line 574, in msgprint
    _raise_exception()
      msg = 'mariadb-dump not found in PATH! This is required to take a backup.'
      title = None
      raise_exception = <class 'frappe.exceptions.ExecutableNotFound'>
      as_table = False
      as_list = False
      indicator = 'red'
      alert = False
      primary_action = None
      is_minimizable = False
      wide = False
      realtime = False
      sys = <module 'sys' (built-in)>
      _raise_exception = <function msgprint.<locals>._raise_exception at 0x109255da0>
      inspect = <module 'inspect' from '/Users/huzaifa/.pyenv/versions/3.11.4/lib/python3.11/inspect.py'>
      out = {'message': 'mariadb-dump not found in PATH! This is required to take a backup.', 'title': 'Message', 'indicator': 'red', 'raise_exception': 1, '__frappe_exc_id': 'df8b233e9eb990fed8b1cf32fc26438a2607c2bdacca3e41a584cedb'}
  File "apps/frappe/frappe/__init__.py", line 525, in _raise_exception
    raise exc
      exc = ExecutableNotFound('mariadb-dump not found in PATH! This is required to take a backup.')
      inspect = <module 'inspect' from '/Users/huzaifa/.pyenv/versions/3.11.4/lib/python3.11/inspect.py'>
      msg = 'mariadb-dump not found in PATH! This is required to take a backup.'
      out = {'message': 'mariadb-dump not found in PATH! This is required to take a backup.', 'title': 'Message', 'indicator': 'red', 'raise_exception': 1, '__frappe_exc_id': 'df8b233e9eb990fed8b1cf32fc26438a2607c2bdacca3e41a584cedb'}
      raise_exception = <class 'frappe.exceptions.ExecutableNotFound'>
frappe.exceptions.ExecutableNotFound: mariadb-dump not found in PATH! This is required to take a backup.
Backup failed for Site learning.test. Database or site_config.json may be corrupted
Traceback with variables (most recent call last):
  File "apps/frappe/frappe/commands/site.py", line 843, in backup
    odb = scheduled_backup(
      context = {'sites': ['learning.test'], 'force': False, 'verbose': True, 'profile': False}
      with_files = False
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_backup_conf = False
      verbose = True
      compress = False
      include = ''
      exclude = ''
      old_backup_metadata = False
      scheduled_backup = <function scheduled_backup at 0x102082660>
      exit_code = 0
      rollback_callback = None
      site = 'learning.test'
  File "apps/frappe/frappe/utils/backups.py", line 568, in scheduled_backup
    return new_backup(
      older_than = 6
      ignore_files = True
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_conf = False
      include_doctypes = ''
      exclude_doctypes = ''
      compress = False
      force = True
      verbose = True
      old_backup_metadata = False
      rollback_callback = <frappe.utils.CallbackManager object at 0x102aee440>
  File "apps/frappe/frappe/utils/backups.py", line 626, in new_backup
    odb.get_backup(older_than, ignore_files, force=force)
      older_than = 6
      ignore_files = True
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_conf = False
      include_doctypes = ''
      exclude_doctypes = ''
      compress = False
      force = True
      verbose = True
      old_backup_metadata = False
      rollback_callback = <frappe.utils.CallbackManager object at 0x102aee440>
      odb = <frappe.utils.backups.BackupGenerator object at 0x102a39310>
  File "apps/frappe/frappe/utils/backups.py", line 195, in get_backup
    self.delete_if_step_fails(self.take_dump, self.backup_path_db)
      self = <frappe.utils.backups.BackupGenerator object at 0x102a39310>
      older_than = 6
      ignore_files = True
      force = True
      last_db = False
      last_file = False
      last_private_file = False
      site_config_backup_path = False
  File "apps/frappe/frappe/utils/backups.py", line 520, in delete_if_step_fails
    raise e
      self = <frappe.utils.backups.BackupGenerator object at 0x102a39310>
      step = <bound method BackupGenerator.take_dump of <frappe.utils.backups.BackupGenerator object at 0x102a39310>>
      paths = ('./learning.test/private/backups/20250708_033001-learning_test-database.sql.gz',)
      path = './learning.test/private/backups/20250708_033001-learning_test-database.sql.gz'
  File "apps/frappe/frappe/utils/backups.py", line 515, in delete_if_step_fails
    step()
      self = <frappe.utils.backups.BackupGenerator object at 0x102a39310>
      step = <bound method BackupGenerator.take_dump of <frappe.utils.backups.BackupGenerator object at 0x102a39310>>
      paths = ('./learning.test/private/backups/20250708_033001-learning_test-database.sql.gz',)
      path = './learning.test/private/backups/20250708_033001-learning_test-database.sql.gz'
  File "apps/frappe/frappe/utils/backups.py", line 457, in take_dump
    frappe.throw(
      self = <frappe.utils.backups.BackupGenerator object at 0x102a39310>
      shlex = <module 'shlex' from '/Users/huzaifa/.pyenv/versions/3.11.4/lib/python3.11/shlex.py'>
      frappe = <module 'frappe' from 'apps/frappe/frappe/__init__.py'>
      get_app_branch = <function get_app_branch at 0x101537e20>
      gzip_exc = '/usr/bin/gzip'
      database_header_content = ['begin frappe metadata', '[frappe]', 'version = 15.71.0', 'branch = version-15', 'end frappe metadata', '']
      generated_header = '-- begin frappe metadata\n-- [frappe]\n-- version = 15.71.0\n-- branch = version-15\n-- end frappe metadata\n-- \n'
      f = <_io.TextIOWrapper name='./learning.test/private/backups/20250708_033001-learning_test-database.sql.gz' encoding='UTF-8'>
      cmd = []
      extra = []
      get_command = <function get_command at 0x102941a80>
      bin = None
      args = ['--user=_e1faab4bbb015fc1', '--host=127.0.0.1', '--port=3306', '--password=hEEDuC879iaZlv31', '--single-transaction', '--quick', '--lock-tables=false', '_e1faab4bbb015fc1']
      bin_name = 'mariadb-dump'
  File "apps/frappe/frappe/__init__.py", line 609, in throw
    msgprint(
      msg = 'mariadb-dump not found in PATH! This is required to take a backup.'
      exc = <class 'frappe.exceptions.ExecutableNotFound'>
      title = None
      is_minimizable = False
      wide = False
      as_list = False
      primary_action = None
  File "apps/frappe/frappe/__init__.py", line 574, in msgprint
    _raise_exception()
      msg = 'mariadb-dump not found in PATH! This is required to take a backup.'
      title = None
      raise_exception = <class 'frappe.exceptions.ExecutableNotFound'>
      as_table = False
      as_list = False
      indicator = 'red'
      alert = False
      primary_action = None
      is_minimizable = False
      wide = False
      realtime = False
      sys = <module 'sys' (built-in)>
      _raise_exception = <function msgprint.<locals>._raise_exception at 0x1014d7d80>
      inspect = <module 'inspect' from '/Users/huzaifa/.pyenv/versions/3.11.4/lib/python3.11/inspect.py'>
      out = {'message': 'mariadb-dump not found in PATH! This is required to take a backup.', 'title': 'Message', 'indicator': 'red', 'raise_exception': 1, '__frappe_exc_id': '2782ff8d2df57f76ac5a1374781da4279651cf82f42115efd0bc5ada'}
  File "apps/frappe/frappe/__init__.py", line 525, in _raise_exception
    raise exc
      exc = ExecutableNotFound('mariadb-dump not found in PATH! This is required to take a backup.')
      inspect = <module 'inspect' from '/Users/huzaifa/.pyenv/versions/3.11.4/lib/python3.11/inspect.py'>
      msg = 'mariadb-dump not found in PATH! This is required to take a backup.'
      out = {'message': 'mariadb-dump not found in PATH! This is required to take a backup.', 'title': 'Message', 'indicator': 'red', 'raise_exception': 1, '__frappe_exc_id': '2782ff8d2df57f76ac5a1374781da4279651cf82f42115efd0bc5ada'}
      raise_exception = <class 'frappe.exceptions.ExecutableNotFound'>
frappe.exceptions.ExecutableNotFound: mariadb-dump not found in PATH! This is required to take a backup.
Backup failed for Site learning.test. Database or site_config.json may be corrupted
Traceback with variables (most recent call last):
  File "apps/frappe/frappe/commands/site.py", line 843, in backup
    odb = scheduled_backup(
      context = {'sites': ['learning.test'], 'force': False, 'verbose': True, 'profile': False}
      with_files = False
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_backup_conf = False
      verbose = True
      compress = False
      include = ''
      exclude = ''
      old_backup_metadata = False
      scheduled_backup = <function scheduled_backup at 0x10412a660>
      exit_code = 0
      rollback_callback = None
      site = 'learning.test'
  File "apps/frappe/frappe/utils/backups.py", line 568, in scheduled_backup
    return new_backup(
      older_than = 6
      ignore_files = True
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_conf = False
      include_doctypes = ''
      exclude_doctypes = ''
      compress = False
      force = True
      verbose = True
      old_backup_metadata = False
      rollback_callback = <frappe.utils.CallbackManager object at 0x104bbe440>
  File "apps/frappe/frappe/utils/backups.py", line 626, in new_backup
    odb.get_backup(older_than, ignore_files, force=force)
      older_than = 6
      ignore_files = True
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_conf = False
      include_doctypes = ''
      exclude_doctypes = ''
      compress = False
      force = True
      verbose = True
      old_backup_metadata = False
      rollback_callback = <frappe.utils.CallbackManager object at 0x104bbe440>
      odb = <frappe.utils.backups.BackupGenerator object at 0x104b092d0>
  File "apps/frappe/frappe/utils/backups.py", line 195, in get_backup
    self.delete_if_step_fails(self.take_dump, self.backup_path_db)
      self = <frappe.utils.backups.BackupGenerator object at 0x104b092d0>
      older_than = 6
      ignore_files = True
      force = True
      last_db = False
      last_file = False
      last_private_file = False
      site_config_backup_path = False
  File "apps/frappe/frappe/utils/backups.py", line 520, in delete_if_step_fails
    raise e
      self = <frappe.utils.backups.BackupGenerator object at 0x104b092d0>
      step = <bound method BackupGenerator.take_dump of <frappe.utils.backups.BackupGenerator object at 0x104b092d0>>
      paths = ('./learning.test/private/backups/20250708_093001-learning_test-database.sql.gz',)
      path = './learning.test/private/backups/20250708_093001-learning_test-database.sql.gz'
  File "apps/frappe/frappe/utils/backups.py", line 515, in delete_if_step_fails
    step()
      self = <frappe.utils.backups.BackupGenerator object at 0x104b092d0>
      step = <bound method BackupGenerator.take_dump of <frappe.utils.backups.BackupGenerator object at 0x104b092d0>>
      paths = ('./learning.test/private/backups/20250708_093001-learning_test-database.sql.gz',)
      path = './learning.test/private/backups/20250708_093001-learning_test-database.sql.gz'
  File "apps/frappe/frappe/utils/backups.py", line 457, in take_dump
    frappe.throw(
      self = <frappe.utils.backups.BackupGenerator object at 0x104b092d0>
      shlex = <module 'shlex' from '/Users/huzaifa/.pyenv/versions/3.11.4/lib/python3.11/shlex.py'>
      frappe = <module 'frappe' from 'apps/frappe/frappe/__init__.py'>
      get_app_branch = <function get_app_branch at 0x10389fe20>
      gzip_exc = '/usr/bin/gzip'
      database_header_content = ['begin frappe metadata', '[frappe]', 'version = 15.71.0', 'branch = version-15', 'end frappe metadata', '']
      generated_header = '-- begin frappe metadata\n-- [frappe]\n-- version = 15.71.0\n-- branch = version-15\n-- end frappe metadata\n-- \n'
      f = <_io.TextIOWrapper name='./learning.test/private/backups/20250708_093001-learning_test-database.sql.gz' encoding='UTF-8'>
      cmd = []
      extra = []
      get_command = <function get_command at 0x104a11a80>
      bin = None
      args = ['--user=_e1faab4bbb015fc1', '--host=127.0.0.1', '--port=3306', '--password=hEEDuC879iaZlv31', '--single-transaction', '--quick', '--lock-tables=false', '_e1faab4bbb015fc1']
      bin_name = 'mariadb-dump'
  File "apps/frappe/frappe/__init__.py", line 609, in throw
    msgprint(
      msg = 'mariadb-dump not found in PATH! This is required to take a backup.'
      exc = <class 'frappe.exceptions.ExecutableNotFound'>
      title = None
      is_minimizable = False
      wide = False
      as_list = False
      primary_action = None
  File "apps/frappe/frappe/__init__.py", line 574, in msgprint
    _raise_exception()
      msg = 'mariadb-dump not found in PATH! This is required to take a backup.'
      title = None
      raise_exception = <class 'frappe.exceptions.ExecutableNotFound'>
      as_table = False
      as_list = False
      indicator = 'red'
      alert = False
      primary_action = None
      is_minimizable = False
      wide = False
      realtime = False
      sys = <module 'sys' (built-in)>
      _raise_exception = <function msgprint.<locals>._raise_exception at 0x10383fd80>
      inspect = <module 'inspect' from '/Users/huzaifa/.pyenv/versions/3.11.4/lib/python3.11/inspect.py'>
      out = {'message': 'mariadb-dump not found in PATH! This is required to take a backup.', 'title': 'Message', 'indicator': 'red', 'raise_exception': 1, '__frappe_exc_id': 'dd1bbe19a019335d46d28d51f0fcace30e920c7240ca3d50a61026ab'}
  File "apps/frappe/frappe/__init__.py", line 525, in _raise_exception
    raise exc
      exc = ExecutableNotFound('mariadb-dump not found in PATH! This is required to take a backup.')
      inspect = <module 'inspect' from '/Users/huzaifa/.pyenv/versions/3.11.4/lib/python3.11/inspect.py'>
      msg = 'mariadb-dump not found in PATH! This is required to take a backup.'
      out = {'message': 'mariadb-dump not found in PATH! This is required to take a backup.', 'title': 'Message', 'indicator': 'red', 'raise_exception': 1, '__frappe_exc_id': 'dd1bbe19a019335d46d28d51f0fcace30e920c7240ca3d50a61026ab'}
      raise_exception = <class 'frappe.exceptions.ExecutableNotFound'>
frappe.exceptions.ExecutableNotFound: mariadb-dump not found in PATH! This is required to take a backup.
Backup failed for Site learning.test. Database or site_config.json may be corrupted
Traceback with variables (most recent call last):
  File "apps/frappe/frappe/commands/site.py", line 843, in backup
    odb = scheduled_backup(
      context = {'sites': ['learning.test'], 'force': False, 'verbose': True, 'profile': False}
      with_files = False
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_backup_conf = False
      verbose = True
      compress = False
      include = ''
      exclude = ''
      old_backup_metadata = False
      scheduled_backup = <function scheduled_backup at 0x1046fa660>
      exit_code = 0
      rollback_callback = None
      site = 'learning.test'
  File "apps/frappe/frappe/utils/backups.py", line 568, in scheduled_backup
    return new_backup(
      older_than = 6
      ignore_files = True
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_conf = False
      include_doctypes = ''
      exclude_doctypes = ''
      compress = False
      force = True
      verbose = True
      old_backup_metadata = False
      rollback_callback = <frappe.utils.CallbackManager object at 0x10518e440>
  File "apps/frappe/frappe/utils/backups.py", line 626, in new_backup
    odb.get_backup(older_than, ignore_files, force=force)
      older_than = 6
      ignore_files = True
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_conf = False
      include_doctypes = ''
      exclude_doctypes = ''
      compress = False
      force = True
      verbose = True
      old_backup_metadata = False
      rollback_callback = <frappe.utils.CallbackManager object at 0x10518e440>
      odb = <frappe.utils.backups.BackupGenerator object at 0x1050d92d0>
  File "apps/frappe/frappe/utils/backups.py", line 195, in get_backup
    self.delete_if_step_fails(self.take_dump, self.backup_path_db)
      self = <frappe.utils.backups.BackupGenerator object at 0x1050d92d0>
      older_than = 6
      ignore_files = True
      force = True
      last_db = False
      last_file = False
      last_private_file = False
      site_config_backup_path = False
  File "apps/frappe/frappe/utils/backups.py", line 520, in delete_if_step_fails
    raise e
      self = <frappe.utils.backups.BackupGenerator object at 0x1050d92d0>
      step = <bound method BackupGenerator.take_dump of <frappe.utils.backups.BackupGenerator object at 0x1050d92d0>>
      paths = ('./learning.test/private/backups/20250708_153001-learning_test-database.sql.gz',)
      path = './learning.test/private/backups/20250708_153001-learning_test-database.sql.gz'
  File "apps/frappe/frappe/utils/backups.py", line 515, in delete_if_step_fails
    step()
      self = <frappe.utils.backups.BackupGenerator object at 0x1050d92d0>
      step = <bound method BackupGenerator.take_dump of <frappe.utils.backups.BackupGenerator object at 0x1050d92d0>>
      paths = ('./learning.test/private/backups/20250708_153001-learning_test-database.sql.gz',)
      path = './learning.test/private/backups/20250708_153001-learning_test-database.sql.gz'
  File "apps/frappe/frappe/utils/backups.py", line 457, in take_dump
    frappe.throw(
      self = <frappe.utils.backups.BackupGenerator object at 0x1050d92d0>
      shlex = <module 'shlex' from '/Users/huzaifa/.pyenv/versions/3.11.4/lib/python3.11/shlex.py'>
      frappe = <module 'frappe' from 'apps/frappe/frappe/__init__.py'>
      get_app_branch = <function get_app_branch at 0x103e6fe20>
      gzip_exc = '/usr/bin/gzip'
      database_header_content = ['begin frappe metadata', '[frappe]', 'version = 15.71.0', 'branch = version-15', 'end frappe metadata', '']
      generated_header = '-- begin frappe metadata\n-- [frappe]\n-- version = 15.71.0\n-- branch = version-15\n-- end frappe metadata\n-- \n'
      f = <_io.TextIOWrapper name='./learning.test/private/backups/20250708_153001-learning_test-database.sql.gz' encoding='UTF-8'>
      cmd = []
      extra = []
      get_command = <function get_command at 0x104fe1a80>
      bin = None
      args = ['--user=_e1faab4bbb015fc1', '--host=127.0.0.1', '--port=3306', '--password=hEEDuC879iaZlv31', '--single-transaction', '--quick', '--lock-tables=false', '_e1faab4bbb015fc1']
      bin_name = 'mariadb-dump'
  File "apps/frappe/frappe/__init__.py", line 609, in throw
    msgprint(
      msg = 'mariadb-dump not found in PATH! This is required to take a backup.'
      exc = <class 'frappe.exceptions.ExecutableNotFound'>
      title = None
      is_minimizable = False
      wide = False
      as_list = False
      primary_action = None
  File "apps/frappe/frappe/__init__.py", line 574, in msgprint
    _raise_exception()
      msg = 'mariadb-dump not found in PATH! This is required to take a backup.'
      title = None
      raise_exception = <class 'frappe.exceptions.ExecutableNotFound'>
      as_table = False
      as_list = False
      indicator = 'red'
      alert = False
      primary_action = None
      is_minimizable = False
      wide = False
      realtime = False
      sys = <module 'sys' (built-in)>
      _raise_exception = <function msgprint.<locals>._raise_exception at 0x103e0fd80>
      inspect = <module 'inspect' from '/Users/huzaifa/.pyenv/versions/3.11.4/lib/python3.11/inspect.py'>
      out = {'message': 'mariadb-dump not found in PATH! This is required to take a backup.', 'title': 'Message', 'indicator': 'red', 'raise_exception': 1, '__frappe_exc_id': '34f9a161c700b95027e1300ebe27b811a1e4ca9151063a8932839565'}
  File "apps/frappe/frappe/__init__.py", line 525, in _raise_exception
    raise exc
      exc = ExecutableNotFound('mariadb-dump not found in PATH! This is required to take a backup.')
      inspect = <module 'inspect' from '/Users/huzaifa/.pyenv/versions/3.11.4/lib/python3.11/inspect.py'>
      msg = 'mariadb-dump not found in PATH! This is required to take a backup.'
      out = {'message': 'mariadb-dump not found in PATH! This is required to take a backup.', 'title': 'Message', 'indicator': 'red', 'raise_exception': 1, '__frappe_exc_id': '34f9a161c700b95027e1300ebe27b811a1e4ca9151063a8932839565'}
      raise_exception = <class 'frappe.exceptions.ExecutableNotFound'>
frappe.exceptions.ExecutableNotFound: mariadb-dump not found in PATH! This is required to take a backup.
Backup failed for Site learning.test. Database or site_config.json may be corrupted
Traceback with variables (most recent call last):
  File "apps/frappe/frappe/commands/site.py", line 843, in backup
    odb = scheduled_backup(
      context = {'sites': ['learning.test'], 'force': False, 'verbose': True, 'profile': False}
      with_files = False
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_backup_conf = False
      verbose = True
      compress = False
      include = ''
      exclude = ''
      old_backup_metadata = False
      scheduled_backup = <function scheduled_backup at 0x104aee660>
      exit_code = 0
      rollback_callback = None
      site = 'learning.test'
  File "apps/frappe/frappe/utils/backups.py", line 568, in scheduled_backup
    return new_backup(
      older_than = 6
      ignore_files = True
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_conf = False
      include_doctypes = ''
      exclude_doctypes = ''
      compress = False
      force = True
      verbose = True
      old_backup_metadata = False
      rollback_callback = <frappe.utils.CallbackManager object at 0x10574a740>
  File "apps/frappe/frappe/utils/backups.py", line 626, in new_backup
    odb.get_backup(older_than, ignore_files, force=force)
      older_than = 6
      ignore_files = True
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_conf = False
      include_doctypes = ''
      exclude_doctypes = ''
      compress = False
      force = True
      verbose = True
      old_backup_metadata = False
      rollback_callback = <frappe.utils.CallbackManager object at 0x10574a740>
      odb = <frappe.utils.backups.BackupGenerator object at 0x104bad210>
  File "apps/frappe/frappe/utils/backups.py", line 195, in get_backup
    self.delete_if_step_fails(self.take_dump, self.backup_path_db)
      self = <frappe.utils.backups.BackupGenerator object at 0x104bad210>
      older_than = 6
      ignore_files = True
      force = True
      last_db = False
      last_file = False
      last_private_file = False
      site_config_backup_path = False
  File "apps/frappe/frappe/utils/backups.py", line 520, in delete_if_step_fails
    raise e
      self = <frappe.utils.backups.BackupGenerator object at 0x104bad210>
      step = <bound method BackupGenerator.take_dump of <frappe.utils.backups.BackupGenerator object at 0x104bad210>>
      paths = ('./learning.test/private/backups/20250708_213001-learning_test-database.sql.gz',)
      path = './learning.test/private/backups/20250708_213001-learning_test-database.sql.gz'
  File "apps/frappe/frappe/utils/backups.py", line 515, in delete_if_step_fails
    step()
      self = <frappe.utils.backups.BackupGenerator object at 0x104bad210>
      step = <bound method BackupGenerator.take_dump of <frappe.utils.backups.BackupGenerator object at 0x104bad210>>
      paths = ('./learning.test/private/backups/20250708_213001-learning_test-database.sql.gz',)
      path = './learning.test/private/backups/20250708_213001-learning_test-database.sql.gz'
  File "apps/frappe/frappe/utils/backups.py", line 457, in take_dump
    frappe.throw(
      self = <frappe.utils.backups.BackupGenerator object at 0x104bad210>
      shlex = <module 'shlex' from '/Users/huzaifa/.pyenv/versions/3.11.4/lib/python3.11/shlex.py'>
      frappe = <module 'frappe' from 'apps/frappe/frappe/__init__.py'>
      get_app_branch = <function get_app_branch at 0x1071245e0>
      gzip_exc = '/usr/bin/gzip'
      database_header_content = ['begin frappe metadata', '[frappe]', 'version = 15.71.0', 'branch = version-15', 'end frappe metadata', '']
      generated_header = '-- begin frappe metadata\n-- [frappe]\n-- version = 15.71.0\n-- branch = version-15\n-- end frappe metadata\n-- \n'
      f = <_io.TextIOWrapper name='./learning.test/private/backups/20250708_213001-learning_test-database.sql.gz' encoding='UTF-8'>
      cmd = []
      extra = []
      get_command = <function get_command at 0x105599a80>
      bin = None
      args = ['--user=_e1faab4bbb015fc1', '--host=127.0.0.1', '--port=3306', '--password=hEEDuC879iaZlv31', '--single-transaction', '--quick', '--lock-tables=false', '_e1faab4bbb015fc1']
      bin_name = 'mariadb-dump'
  File "apps/frappe/frappe/__init__.py", line 609, in throw
    msgprint(
      msg = 'mariadb-dump not found in PATH! This is required to take a backup.'
      exc = <class 'frappe.exceptions.ExecutableNotFound'>
      title = None
      is_minimizable = False
      wide = False
      as_list = False
      primary_action = None
  File "apps/frappe/frappe/__init__.py", line 574, in msgprint
    _raise_exception()
      msg = 'mariadb-dump not found in PATH! This is required to take a backup.'
      title = None
      raise_exception = <class 'frappe.exceptions.ExecutableNotFound'>
      as_table = False
      as_list = False
      indicator = 'red'
      alert = False
      primary_action = None
      is_minimizable = False
      wide = False
      realtime = False
      sys = <module 'sys' (built-in)>
      _raise_exception = <function msgprint.<locals>._raise_exception at 0x107555da0>
      inspect = <module 'inspect' from '/Users/huzaifa/.pyenv/versions/3.11.4/lib/python3.11/inspect.py'>
      out = {'message': 'mariadb-dump not found in PATH! This is required to take a backup.', 'title': 'Message', 'indicator': 'red', 'raise_exception': 1, '__frappe_exc_id': '114c5294734786406d21575b00fd2e44c4ed25c5ec7de93d96332d2a'}
  File "apps/frappe/frappe/__init__.py", line 525, in _raise_exception
    raise exc
      exc = ExecutableNotFound('mariadb-dump not found in PATH! This is required to take a backup.')
      inspect = <module 'inspect' from '/Users/huzaifa/.pyenv/versions/3.11.4/lib/python3.11/inspect.py'>
      msg = 'mariadb-dump not found in PATH! This is required to take a backup.'
      out = {'message': 'mariadb-dump not found in PATH! This is required to take a backup.', 'title': 'Message', 'indicator': 'red', 'raise_exception': 1, '__frappe_exc_id': '114c5294734786406d21575b00fd2e44c4ed25c5ec7de93d96332d2a'}
      raise_exception = <class 'frappe.exceptions.ExecutableNotFound'>
frappe.exceptions.ExecutableNotFound: mariadb-dump not found in PATH! This is required to take a backup.
Backup failed for Site learning.test. Database or site_config.json may be corrupted
Traceback with variables (most recent call last):
  File "apps/frappe/frappe/commands/site.py", line 843, in backup
    odb = scheduled_backup(
      context = {'sites': ['learning.test'], 'force': False, 'verbose': True, 'profile': False}
      with_files = False
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_backup_conf = False
      verbose = True
      compress = False
      include = ''
      exclude = ''
      old_backup_metadata = False
      scheduled_backup = <function scheduled_backup at 0x102682660>
      exit_code = 0
      rollback_callback = None
      site = 'learning.test'
  File "apps/frappe/frappe/utils/backups.py", line 568, in scheduled_backup
    return new_backup(
      older_than = 6
      ignore_files = True
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_conf = False
      include_doctypes = ''
      exclude_doctypes = ''
      compress = False
      force = True
      verbose = True
      old_backup_metadata = False
      rollback_callback = <frappe.utils.CallbackManager object at 0x1030ee740>
  File "apps/frappe/frappe/utils/backups.py", line 626, in new_backup
    odb.get_backup(older_than, ignore_files, force=force)
      older_than = 6
      ignore_files = True
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_conf = False
      include_doctypes = ''
      exclude_doctypes = ''
      compress = False
      force = True
      verbose = True
      old_backup_metadata = False
      rollback_callback = <frappe.utils.CallbackManager object at 0x1030ee740>
      odb = <frappe.utils.backups.BackupGenerator object at 0x102be93d0>
  File "apps/frappe/frappe/utils/backups.py", line 195, in get_backup
    self.delete_if_step_fails(self.take_dump, self.backup_path_db)
      self = <frappe.utils.backups.BackupGenerator object at 0x102be93d0>
      older_than = 6
      ignore_files = True
      force = True
      last_db = False
      last_file = False
      last_private_file = False
      site_config_backup_path = False
  File "apps/frappe/frappe/utils/backups.py", line 520, in delete_if_step_fails
    raise e
      self = <frappe.utils.backups.BackupGenerator object at 0x102be93d0>
      step = <bound method BackupGenerator.take_dump of <frappe.utils.backups.BackupGenerator object at 0x102be93d0>>
      paths = ('./learning.test/private/backups/20250710_213002-learning_test-database.sql.gz',)
      path = './learning.test/private/backups/20250710_213002-learning_test-database.sql.gz'
  File "apps/frappe/frappe/utils/backups.py", line 515, in delete_if_step_fails
    step()
      self = <frappe.utils.backups.BackupGenerator object at 0x102be93d0>
      step = <bound method BackupGenerator.take_dump of <frappe.utils.backups.BackupGenerator object at 0x102be93d0>>
      paths = ('./learning.test/private/backups/20250710_213002-learning_test-database.sql.gz',)
      path = './learning.test/private/backups/20250710_213002-learning_test-database.sql.gz'
  File "apps/frappe/frappe/utils/backups.py", line 457, in take_dump
    frappe.throw(
      self = <frappe.utils.backups.BackupGenerator object at 0x102be93d0>
      shlex = <module 'shlex' from '/Users/huzaifa/.pyenv/versions/3.11.4/lib/python3.11/shlex.py'>
      frappe = <module 'frappe' from 'apps/frappe/frappe/__init__.py'>
      get_app_branch = <function get_app_branch at 0x104ba45e0>
      gzip_exc = '/usr/bin/gzip'
      database_header_content = ['begin frappe metadata', '[frappe]', 'version = 15.71.0', 'branch = version-15', 'end frappe metadata', '']
      generated_header = '-- begin frappe metadata\n-- [frappe]\n-- version = 15.71.0\n-- branch = version-15\n-- end frappe metadata\n-- \n'
      f = <_io.TextIOWrapper name='./learning.test/private/backups/20250710_213002-learning_test-database.sql.gz' encoding='UTF-8'>
      cmd = []
      extra = []
      get_command = <function get_command at 0x102f41a80>
      bin = None
      args = ['--user=_e1faab4bbb015fc1', '--host=127.0.0.1', '--port=3306', '--password=hEEDuC879iaZlv31', '--single-transaction', '--quick', '--lock-tables=false', '_e1faab4bbb015fc1']
      bin_name = 'mariadb-dump'
  File "apps/frappe/frappe/__init__.py", line 609, in throw
    msgprint(
      msg = 'mariadb-dump not found in PATH! This is required to take a backup.'
      exc = <class 'frappe.exceptions.ExecutableNotFound'>
      title = None
      is_minimizable = False
      wide = False
      as_list = False
      primary_action = None
  File "apps/frappe/frappe/__init__.py", line 574, in msgprint
    _raise_exception()
      msg = 'mariadb-dump not found in PATH! This is required to take a backup.'
      title = None
      raise_exception = <class 'frappe.exceptions.ExecutableNotFound'>
      as_table = False
      as_list = False
      indicator = 'red'
      alert = False
      primary_action = None
      is_minimizable = False
      wide = False
      realtime = False
      sys = <module 'sys' (built-in)>
      _raise_exception = <function msgprint.<locals>._raise_exception at 0x104e1dda0>
      inspect = <module 'inspect' from '/Users/huzaifa/.pyenv/versions/3.11.4/lib/python3.11/inspect.py'>
      out = {'message': 'mariadb-dump not found in PATH! This is required to take a backup.', 'title': 'Message', 'indicator': 'red', 'raise_exception': 1, '__frappe_exc_id': '1864aef42d884d1842f93d7f3bbe77246f463722dc76cd04a7cd67a9'}
  File "apps/frappe/frappe/__init__.py", line 525, in _raise_exception
    raise exc
      exc = ExecutableNotFound('mariadb-dump not found in PATH! This is required to take a backup.')
      inspect = <module 'inspect' from '/Users/huzaifa/.pyenv/versions/3.11.4/lib/python3.11/inspect.py'>
      msg = 'mariadb-dump not found in PATH! This is required to take a backup.'
      out = {'message': 'mariadb-dump not found in PATH! This is required to take a backup.', 'title': 'Message', 'indicator': 'red', 'raise_exception': 1, '__frappe_exc_id': '1864aef42d884d1842f93d7f3bbe77246f463722dc76cd04a7cd67a9'}
      raise_exception = <class 'frappe.exceptions.ExecutableNotFound'>
frappe.exceptions.ExecutableNotFound: mariadb-dump not found in PATH! This is required to take a backup.
